// lib/dsa-data.ts — All 502 questions from the DSA Master Sheet

export interface Question {
  id: number
  subId: number
  subtopic: string
  name: string
  difficulty: number  // 1-5 stars
  link?: string
  code?: string
  explanation?: string
  approach?: string
  timeComplexity?: string
  spaceComplexity?: string
}

export interface Topic {
  name: string
  slug: string
  icon: string
  subtopics?: string[]
  questions: Question[]
}

export interface Phase {
  title: string
  color: string
  topics: Topic[]
}

export const PHASE_COLORS: Record<string, string> = {
  'Phase 1': '#6366f1',
  'Phase 2': '#06b6d4',
  'Phase 3': '#10b981',
  'Phase 4': '#a855f7',
  'Phase 5': '#f59e0b',
  'Phase 6': '#ef4444',
  'Phase 7': '#f97316',
  'Phase 8': '#84cc16',
  'Phase 9': '#ec4899',
}

export const DSA_DATA: Record<string, Phase> = {
  'Phase 1': {
    title: 'Fundamentals & Linear Data Structures',
    color: '#6366f1',
    topics: [
      {
        name: 'Arrays',
        slug: 'arrays',
        icon: '[]',
        subtopics: ['Array Basics', 'Core Manipulations', 'Intermediate', 'Advanced'],
        questions: [
          { id: 1, subId: 1, subtopic: 'Array Basics', name: 'Find Element at a Given Index', difficulty: 1 },
          { id: 2, subId: 2, subtopic: 'Array Basics', name: 'Min and Max in Array', difficulty: 1 },
          { id: 3, subId: 3, subtopic: 'Array Basics', name: 'Sum of Array', difficulty: 1 },
          { id: 4, subId: 4, subtopic: 'Array Basics', name: 'Sum of Digits', difficulty: 1 },
          { id: 5, subId: 5, subtopic: 'Array Basics', name: 'Check If Array is Sorted', difficulty: 1 },
          { id: 6, subId: 6, subtopic: 'Array Basics', name: 'Alternates In Array', difficulty: 1 },
          { id: 7, subId: 7, subtopic: 'Core Manipulations', name: 'Remove Duplicates from Array', difficulty: 2 },
          { id: 8, subId: 8, subtopic: 'Core Manipulations', name: 'Second Largest in Array', difficulty: 2 },
          { id: 9, subId: 9, subtopic: 'Core Manipulations', name: 'Reverse an Array', difficulty: 2 },
          { id: 10, subId: 10, subtopic: 'Core Manipulations', name: 'Missing Number', difficulty: 2 },
          { id: 11, subId: 11, subtopic: 'Core Manipulations', name: 'Segregate 0s and 1s', difficulty: 2 },
          { id: 12, subId: 12, subtopic: 'Core Manipulations', name: 'Maximum Consecutive Ones', difficulty: 2 },
          { id: 13, subId: 13, subtopic: 'Core Manipulations', name: 'Palindromic Array', difficulty: 2 },
          { id: 14, subId: 14, subtopic: 'Core Manipulations', name: 'Move Zeroes to End', difficulty: 2 },
          { id: 15, subId: 15, subtopic: 'Core Manipulations', name: 'Sort array with 0s 1s and 2s (Dutch Flag)', difficulty: 2 },
          { id: 16, subId: 16, subtopic: 'Intermediate', name: 'Equilibrium Point', difficulty: 3 },
          { id: 17, subId: 17, subtopic: 'Intermediate', name: 'Reverse Integer', difficulty: 3 },
          { id: 18, subId: 18, subtopic: 'Intermediate', name: 'Leaders in Array', difficulty: 3 },
          { id: 19, subId: 19, subtopic: 'Intermediate', name: 'Increasing Array', difficulty: 3 },
          { id: 20, subId: 20, subtopic: 'Intermediate', name: 'Rearrange Array Elements by Sign', difficulty: 3 },
          { id: 21, subId: 21, subtopic: 'Intermediate', name: 'Rotate Array by One', difficulty: 3 },
          { id: 22, subId: 22, subtopic: 'Intermediate', name: 'Majority Element I (Boyer-Moore)', difficulty: 3 },
          { id: 23, subId: 23, subtopic: 'Advanced', name: 'Rotate Array by K steps', difficulty: 4 },
          { id: 24, subId: 24, subtopic: 'Advanced', name: 'Wiggle Sort II', difficulty: 4 },
          { id: 25, subId: 25, subtopic: 'Advanced', name: 'Majority Element II', difficulty: 4 },
          { id: 26, subId: 26, subtopic: 'Advanced', name: 'Best Time to Buy and Sell Stock', difficulty: 4 },
          { id: 27, subId: 27, subtopic: 'Advanced', name: 'Next Permutation', difficulty: 4 },
          { id: 28, subId: 28, subtopic: 'Advanced', name: 'Maximum Value Of Expression', difficulty: 4 },
          { id: 29, subId: 29, subtopic: 'Advanced', name: 'First Missing Positive', difficulty: 5 },
        ]
      },
      {
        name: '2D Arrays',
        slug: '2d-arrays',
        icon: '⬛',
        subtopics: ['Matrix Basics', 'Matrix Operations', 'Advanced Matrix'],
        questions: [
          { id: 30, subId: 1, subtopic: 'Matrix Basics', name: 'Sum of elements in a matrix', difficulty: 2 },
          { id: 31, subId: 2, subtopic: 'Matrix Basics', name: 'Count Number Of Zeroes', difficulty: 2 },
          { id: 32, subId: 3, subtopic: 'Matrix Basics', name: 'Count Negative Numbers in a matrix', difficulty: 2 },
          { id: 33, subId: 4, subtopic: 'Matrix Basics', name: 'Matrix Diagonal Sum', difficulty: 2 },
          { id: 34, subId: 5, subtopic: 'Matrix Operations', name: 'Addition of Two Square Matrix', difficulty: 3 },
          { id: 35, subId: 6, subtopic: 'Matrix Operations', name: 'Multiply Matrices', difficulty: 3 },
          { id: 36, subId: 7, subtopic: 'Matrix Operations', name: 'Transpose Matrix', difficulty: 3 },
          { id: 37, subId: 8, subtopic: 'Advanced Matrix', name: 'Spiral Matrix', difficulty: 4 },
          { id: 38, subId: 9, subtopic: 'Advanced Matrix', name: 'ZigZag Matrix', difficulty: 4 },
          { id: 39, subId: 10, subtopic: 'Advanced Matrix', name: 'Rotate Matrix (90°)', difficulty: 4 },
          { id: 40, subId: 11, subtopic: 'Advanced Matrix', name: 'Determine Whether matrix can be obtained by rotation', difficulty: 4 },
          { id: 41, subId: 12, subtopic: 'Advanced Matrix', name: 'Set Matrix Zeroes', difficulty: 5 },
        ]
      },
      {
        name: 'Basic Maths',
        slug: 'basic-maths',
        icon: '🔢',
        subtopics: ['Number Theory'],
        questions: [
          { id: 42, subId: 1, subtopic: 'Number Theory', name: 'Check if a number is Armstrong', difficulty: 1 },
          { id: 43, subId: 2, subtopic: 'Number Theory', name: 'Print all Divisors of a Number', difficulty: 1 },
          { id: 44, subId: 3, subtopic: 'Number Theory', name: 'Check if a number is Prime', difficulty: 1 },
          { id: 45, subId: 4, subtopic: 'Number Theory', name: 'GCD / HCF of 2 numbers', difficulty: 1 },
          { id: 46, subId: 5, subtopic: 'Number Theory', name: 'Prime Factorisation of a Number', difficulty: 2 },
          { id: 47, subId: 6, subtopic: 'Number Theory', name: 'Count Primes in range L to R', difficulty: 3 },
        ]
      },
      {
        name: 'Strings',
        slug: 'strings',
        icon: '📝',
        subtopics: ['Fundamentals', 'Manipulation', 'Advanced'],
        questions: [
          { id: 48, subId: 1, subtopic: 'Fundamentals', name: 'Maximum Occuring Character', difficulty: 1 },
          { id: 49, subId: 2, subtopic: 'Fundamentals', name: 'Remove Spaces', difficulty: 1 },
          { id: 50, subId: 3, subtopic: 'Fundamentals', name: 'Print first letter of every word', difficulty: 2 },
          { id: 51, subId: 4, subtopic: 'Fundamentals', name: 'Remove Consecutive Characters', difficulty: 2 },
          { id: 52, subId: 5, subtopic: 'Fundamentals', name: 'Valid Palindrome', difficulty: 2 },
          { id: 53, subId: 6, subtopic: 'Fundamentals', name: 'Valid Anagram', difficulty: 2 },
          { id: 54, subId: 7, subtopic: 'Fundamentals', name: 'Isomorphic Strings', difficulty: 2 },
          { id: 55, subId: 8, subtopic: 'Manipulation', name: 'Delete Characters To Make Fancy String', difficulty: 3 },
          { id: 56, subId: 9, subtopic: 'Manipulation', name: 'Reverse Words in a String', difficulty: 3 },
          { id: 57, subId: 10, subtopic: 'Manipulation', name: 'String to integer (atoi)', difficulty: 3 },
          { id: 58, subId: 11, subtopic: 'Manipulation', name: 'Roman to integer', difficulty: 3 },
          { id: 59, subId: 12, subtopic: 'Manipulation', name: 'Rotate String', difficulty: 3 },
          { id: 60, subId: 13, subtopic: 'Manipulation', name: 'Longest common prefix', difficulty: 3 },
          { id: 61, subId: 14, subtopic: 'Advanced', name: 'Longest palindromic substring', difficulty: 4 },
          { id: 62, subId: 15, subtopic: 'Advanced', name: 'Multiply Two Strings', difficulty: 4 },
          { id: 63, subId: 16, subtopic: 'Advanced', name: 'Maximum Nesting Depth of the Parentheses', difficulty: 4 },
          { id: 64, subId: 17, subtopic: 'Advanced', name: 'Beauty Of All substrings', difficulty: 4 },
        ]
      },
    ]
  },
  'Phase 2': {
    title: 'Searching Algorithms',
    color: '#06b6d4',
    topics: [
      {
        name: 'Binary Search',
        slug: 'binary-search',
        icon: '🔍',
        subtopics: ['1D Array Basics', '1D Intermediate', '2D Arrays', 'BS on Answer'],
        questions: [
          { id: 65, subId: 1, subtopic: '1D Array Basics', name: 'Search X in sorted array', difficulty: 2 },
          { id: 66, subId: 2, subtopic: '1D Array Basics', name: 'Lower Bound', difficulty: 2 },
          { id: 67, subId: 3, subtopic: '1D Array Basics', name: 'Upper Bound', difficulty: 2 },
          { id: 68, subId: 4, subtopic: '1D Array Basics', name: 'Search insert position', difficulty: 2 },
          { id: 69, subId: 5, subtopic: '1D Array Basics', name: 'Floor In Sorted Array', difficulty: 2 },
          { id: 70, subId: 6, subtopic: '1D Array Basics', name: 'Ceil In Sorted Array', difficulty: 2 },
          { id: 71, subId: 7, subtopic: '1D Array Basics', name: 'Guess Number Higher or Lower API', difficulty: 2 },
          { id: 72, subId: 8, subtopic: '1D Array Basics', name: 'First 1 in a Sorted Binary Array', difficulty: 2 },
          { id: 73, subId: 9, subtopic: '1D Array Basics', name: 'Kth Missing Positive Number', difficulty: 2 },
          { id: 74, subId: 10, subtopic: '1D Array Basics', name: 'Find minimum in Rotated Sorted Array', difficulty: 2 },
          { id: 75, subId: 11, subtopic: '1D Intermediate', name: 'First and last occurrence', difficulty: 3 },
          { id: 76, subId: 12, subtopic: '1D Intermediate', name: 'Search in rotated sorted array-I', difficulty: 3 },
          { id: 77, subId: 13, subtopic: '1D Intermediate', name: 'Search in rotated sorted array-II', difficulty: 3 },
          { id: 78, subId: 14, subtopic: '1D Intermediate', name: 'Single element in a Sorted Array', difficulty: 3 },
          { id: 79, subId: 15, subtopic: '1D Intermediate', name: 'Find kth Rotation', difficulty: 3 },
          { id: 80, subId: 16, subtopic: '1D Intermediate', name: 'Find Peak Element', difficulty: 3 },
          { id: 81, subId: 17, subtopic: '2D Arrays', name: 'Count Negative Numbers in a Sorted Matrix', difficulty: 2 },
          { id: 82, subId: 18, subtopic: '2D Arrays', name: 'Find row with maximum 1s', difficulty: 2 },
          { id: 83, subId: 19, subtopic: '2D Arrays', name: 'Search a 2D Matrix I', difficulty: 2 },
          { id: 84, subId: 20, subtopic: '2D Arrays', name: 'Search a 2D Matrix II', difficulty: 3 },
          { id: 85, subId: 21, subtopic: '2D Arrays', name: 'Find Peak Element II', difficulty: 4 },
          { id: 86, subId: 22, subtopic: '2D Arrays', name: 'Median in a row-wise sorted Matrix', difficulty: 4 },
          { id: 87, subId: 23, subtopic: 'BS on Answer', name: 'Sqrt(x)', difficulty: 2 },
          { id: 88, subId: 24, subtopic: 'BS on Answer', name: 'Valid Perfect Square', difficulty: 2 },
          { id: 89, subId: 25, subtopic: 'BS on Answer', name: 'Find Nth root of a number', difficulty: 3 },
          { id: 90, subId: 26, subtopic: 'BS on Answer', name: 'Koko eating bananas', difficulty: 3 },
          { id: 91, subId: 27, subtopic: 'BS on Answer', name: 'Find the Smallest Divisor Given a Threshold', difficulty: 3 },
          { id: 92, subId: 28, subtopic: 'BS on Answer', name: 'Minimum Speed to Arrive on Time', difficulty: 3 },
          { id: 93, subId: 29, subtopic: 'BS on Answer', name: 'Minimum days to make M bouquets', difficulty: 3 },
          { id: 94, subId: 30, subtopic: 'BS on Answer', name: 'Capacity to Ship Packages Within D Days', difficulty: 3 },
          { id: 95, subId: 31, subtopic: 'BS on Answer', name: 'Book Allocation Problem', difficulty: 3 },
          { id: 96, subId: 32, subtopic: 'BS on Answer', name: 'Split Array Largest Sum', difficulty: 4 },
          { id: 97, subId: 33, subtopic: 'BS on Answer', name: "Painter's Partition Problem", difficulty: 4 },
          { id: 98, subId: 34, subtopic: 'BS on Answer', name: 'K-th element of two sorted Arrays', difficulty: 4 },
          { id: 99, subId: 35, subtopic: 'BS on Answer', name: 'Aggressive Cows', difficulty: 5 },
          { id: 100, subId: 36, subtopic: 'BS on Answer', name: 'Minimize Max Distance to Gas Station', difficulty: 5 },
          { id: 101, subId: 37, subtopic: 'BS on Answer', name: 'Median of Two Sorted Arrays', difficulty: 5 },
        ]
      },
    ]
  },
  'Phase 3': {
    title: 'Algorithmic Thinking',
    color: '#10b981',
    topics: [
      {
        name: 'Recursion',
        slug: 'recursion',
        icon: '🔄',
        subtopics: ['Introduction', 'Recursion on Arrays & Math', 'Recursion On Strings'],
        questions: [
          { id: 102, subId: 1, subtopic: 'Introduction', name: 'Print 1 to N without using loops', difficulty: 1 },
          { id: 103, subId: 2, subtopic: 'Introduction', name: 'Print N to 1 without loop', difficulty: 1 },
          { id: 104, subId: 3, subtopic: 'Introduction', name: 'Sum of first N numbers', difficulty: 1 },
          { id: 105, subId: 4, subtopic: 'Introduction', name: 'Factorial of a given number', difficulty: 1 },
          { id: 106, subId: 5, subtopic: 'Introduction', name: 'Fibonacci Number', difficulty: 1 },
          { id: 107, subId: 6, subtopic: 'Arrays & Math', name: 'Reverse an array', difficulty: 2 },
          { id: 108, subId: 7, subtopic: 'Arrays & Math', name: 'Pow(x, n)', difficulty: 2 },
          { id: 109, subId: 8, subtopic: 'Arrays & Math', name: 'Count Good Numbers', difficulty: 2 },
          { id: 110, subId: 9, subtopic: 'Arrays & Math', name: 'Recursive Implementation of atoi()', difficulty: 3 },
          { id: 111, subId: 10, subtopic: 'Strings', name: 'Generate Binary Strings Without Consecutive 1s', difficulty: 3 },
        ]
      },
      {
        name: 'Sorting',
        slug: 'sorting',
        icon: '🔀',
        subtopics: ['Fundamentals', 'Custom Comparator', 'Advanced Sorting'],
        questions: [
          { id: 112, subId: 1, subtopic: 'Fundamentals', name: 'Linear Search', difficulty: 1 },
          { id: 113, subId: 2, subtopic: 'Fundamentals', name: 'Sort An Array (Implement Merge / Quick Sort)', difficulty: 2 },
          { id: 114, subId: 3, subtopic: 'Fundamentals', name: 'Sort Array By Parity', difficulty: 2 },
          { id: 115, subId: 4, subtopic: 'Fundamentals', name: 'Maximum Gap', difficulty: 3 },
          { id: 116, subId: 5, subtopic: 'Custom Comparator', name: 'Sort Elements by Decreasing Frequency', difficulty: 3 },
          { id: 117, subId: 6, subtopic: 'Custom Comparator', name: 'Reorder Data In Log Files', difficulty: 4 },
          { id: 118, subId: 7, subtopic: 'Advanced', name: 'Merge Intervals', difficulty: 3 },
          { id: 119, subId: 8, subtopic: 'Advanced', name: 'Count Inversions (Merge Sort)', difficulty: 5 },
          { id: 120, subId: 9, subtopic: 'Advanced', name: 'Reverse Pairs (Merge Sort)', difficulty: 5 },
        ]
      },
    ]
  },
  'Phase 4': {
    title: 'Object Oriented Concepts',
    color: '#a855f7',
    topics: [
      {
        name: 'OOPS',
        slug: 'oops',
        icon: '🧩',
        subtopics: ['Fundamentals', 'Design Patterns'],
        questions: [
          { id: 121, subId: 1, subtopic: 'Fundamentals', name: 'Classes, Objects & Constructors', difficulty: 1 },
          { id: 122, subId: 2, subtopic: 'Fundamentals', name: 'Inheritance & Polymorphism', difficulty: 2 },
          { id: 123, subId: 3, subtopic: 'Fundamentals', name: 'Encapsulation & Abstraction', difficulty: 2 },
          { id: 124, subId: 4, subtopic: 'Fundamentals', name: 'Interfaces & Abstract Classes', difficulty: 3 },
          { id: 125, subId: 5, subtopic: 'Design Patterns', name: 'Singleton Pattern', difficulty: 3 },
          { id: 126, subId: 6, subtopic: 'Design Patterns', name: 'Factory Pattern', difficulty: 4 },
        ]
      },
    ]
  },
  'Phase 5': {
    title: 'Advanced Linear Data Structures',
    color: '#f59e0b',
    topics: [
      {
        name: 'Linked List',
        slug: 'linked-list',
        icon: '⛓️',
        subtopics: ['Foundation', 'Insertion & Deletion', 'Fast & Slow Pointer', 'Reversals', 'Math', 'Sorting & Merging', 'Doubly Linked List', 'Advanced'],
        questions: [
          { id: 127, subId: 1, subtopic: 'Foundation', name: 'Array to Linked List', difficulty: 1 },
          { id: 128, subId: 2, subtopic: 'Foundation', name: 'Count Nodes / Find Length', difficulty: 1 },
          { id: 129, subId: 3, subtopic: 'Foundation', name: 'Search in a Linked List', difficulty: 1 },
          { id: 130, subId: 4, subtopic: 'Insertion & Deletion', name: 'Insert Node at Head / Tail', difficulty: 2 },
          { id: 131, subId: 5, subtopic: 'Insertion & Deletion', name: 'Insert in Middle of Linked List', difficulty: 2 },
          { id: 132, subId: 6, subtopic: 'Insertion & Deletion', name: 'Remove Linked List Elements (By Value)', difficulty: 2 },
          { id: 133, subId: 7, subtopic: 'Insertion & Deletion', name: 'Remove Duplicates from Sorted List', difficulty: 2 },
          { id: 134, subId: 8, subtopic: 'Insertion & Deletion', name: 'Delete Node in a Linked List', difficulty: 3 },
          { id: 135, subId: 9, subtopic: 'Insertion & Deletion', name: 'Remove Duplicates from Unsorted List', difficulty: 3 },
          { id: 136, subId: 10, subtopic: 'Insertion & Deletion', name: 'Delete the Middle Node', difficulty: 3 },
          { id: 137, subId: 11, subtopic: 'Fast & Slow Pointer', name: 'Middle of the Linked List', difficulty: 2 },
          { id: 138, subId: 12, subtopic: 'Fast & Slow Pointer', name: 'Linked List Cycle', difficulty: 2 },
          { id: 139, subId: 13, subtopic: 'Fast & Slow Pointer', name: 'Intersection of Two Linked Lists', difficulty: 2 },
          { id: 140, subId: 14, subtopic: 'Fast & Slow Pointer', name: 'Length of Loop in Linked List', difficulty: 3 },
          { id: 141, subId: 15, subtopic: 'Fast & Slow Pointer', name: 'Linked List Cycle II (Find Starting Point)', difficulty: 3 },
          { id: 142, subId: 16, subtopic: 'Fast & Slow Pointer', name: 'Remove Loop in Linked List', difficulty: 3 },
          { id: 143, subId: 17, subtopic: 'Fast & Slow Pointer', name: 'Remove Nth Node From End of List', difficulty: 3 },
          { id: 144, subId: 18, subtopic: 'Reversals', name: 'Reverse a Linked List (Iterative & Recursive)', difficulty: 2 },
          { id: 145, subId: 19, subtopic: 'Reversals', name: 'Palindrome Linked List', difficulty: 2 },
          { id: 146, subId: 20, subtopic: 'Reversals', name: 'Swap Nodes in Pairs', difficulty: 3 },
          { id: 147, subId: 21, subtopic: 'Reversals', name: 'Odd Even Linked List (By Index)', difficulty: 3 },
          { id: 148, subId: 22, subtopic: 'Reversals', name: 'Reorder List', difficulty: 4 },
          { id: 149, subId: 23, subtopic: 'Reversals', name: 'Rotate List', difficulty: 4 },
          { id: 150, subId: 24, subtopic: 'Math', name: 'Add One to a Number Represented by LL', difficulty: 3 },
          { id: 151, subId: 25, subtopic: 'Math', name: 'Add Two Numbers (Reverse Order)', difficulty: 3 },
          { id: 152, subId: 26, subtopic: 'Math', name: 'Add Two Numbers II (Forward Order)', difficulty: 4 },
          { id: 153, subId: 27, subtopic: 'Sorting & Merging', name: 'Merge Two Sorted Lists', difficulty: 2 },
          { id: 154, subId: 28, subtopic: 'Sorting & Merging', name: 'Sort a Linked List of 0s, 1s, and 2s', difficulty: 3 },
          { id: 155, subId: 29, subtopic: 'Sorting & Merging', name: 'Segregate Even and Odd Nodes', difficulty: 3 },
          { id: 156, subId: 30, subtopic: 'Sorting & Merging', name: 'Partition List', difficulty: 4 },
          { id: 157, subId: 31, subtopic: 'Sorting & Merging', name: 'Insertion Sort List', difficulty: 4 },
          { id: 158, subId: 32, subtopic: 'Sorting & Merging', name: 'Sort List (Merge Sort on LL)', difficulty: 5 },
          { id: 159, subId: 33, subtopic: 'Doubly Linked List', name: 'Array to Doubly Linked List', difficulty: 1 },
          { id: 160, subId: 34, subtopic: 'Doubly Linked List', name: 'Insert/Delete in a Doubly Linked List', difficulty: 2 },
          { id: 161, subId: 35, subtopic: 'Doubly Linked List', name: 'Reverse a Doubly Linked List', difficulty: 2 },
          { id: 162, subId: 36, subtopic: 'Doubly Linked List', name: 'Remove Duplicates from Sorted DLL', difficulty: 2 },
          { id: 163, subId: 37, subtopic: 'Doubly Linked List', name: 'Insert in Sorted way in a Sorted DLL', difficulty: 3 },
          { id: 164, subId: 38, subtopic: 'Doubly Linked List', name: 'Delete all occurrences of a key in DLL', difficulty: 3 },
          { id: 165, subId: 39, subtopic: 'Doubly Linked List', name: 'Find Pairs with Given Sum in a DLL', difficulty: 3 },
          { id: 166, subId: 40, subtopic: 'Advanced', name: 'Copy List with Random Pointer (Clone LL)', difficulty: 4 },
          { id: 167, subId: 41, subtopic: 'Advanced', name: 'Flattening a Linked List', difficulty: 4 },
          { id: 168, subId: 42, subtopic: 'Advanced', name: 'Reverse Linked List in Groups of Size K', difficulty: 5 },
          { id: 169, subId: 43, subtopic: 'Advanced', name: 'Reverse Alternate K Nodes', difficulty: 5 },
        ]
      },
      {
        name: 'Stacks',
        slug: 'stacks',
        icon: '📚',
        subtopics: ['Core Implementation', 'Parentheses & Parsing', 'Monotonic Stack', 'Classic Design'],
        questions: [
          { id: 170, subId: 1, subtopic: 'Core', name: 'Implement Stack using Arrays', difficulty: 1 },
          { id: 171, subId: 2, subtopic: 'Core', name: 'Implement Stack using Linked List', difficulty: 1 },
          { id: 172, subId: 3, subtopic: 'Parentheses', name: 'Valid Parentheses', difficulty: 2 },
          { id: 173, subId: 4, subtopic: 'Parentheses', name: 'Remove Outermost Parentheses', difficulty: 2 },
          { id: 174, subId: 5, subtopic: 'Parentheses', name: 'Remove All Adjacent Duplicates In String', difficulty: 2 },
          { id: 175, subId: 6, subtopic: 'Parentheses', name: 'Minimum Add to Make Parentheses Valid', difficulty: 2 },
          { id: 176, subId: 7, subtopic: 'Parentheses', name: 'Minimum Remove to Make Valid Parentheses', difficulty: 3 },
          { id: 177, subId: 8, subtopic: 'Parentheses', name: 'Evaluate Reverse Polish Notation', difficulty: 3 },
          { id: 178, subId: 9, subtopic: 'Recursion', name: 'Sort a Stack Using Recursion', difficulty: 3 },
          { id: 179, subId: 10, subtopic: 'Recursion', name: 'Reverse a Stack (Using Recursion)', difficulty: 3 },
          { id: 180, subId: 11, subtopic: 'Expression', name: 'Infix to Postfix Conversion', difficulty: 2 },
          { id: 181, subId: 12, subtopic: 'Expression', name: 'Prefix to Infix Conversion', difficulty: 2 },
          { id: 182, subId: 13, subtopic: 'Expression', name: 'Postfix to Prefix Conversion', difficulty: 2 },
          { id: 183, subId: 14, subtopic: 'Expression', name: 'Infix to Prefix Conversion', difficulty: 3 },
          { id: 184, subId: 15, subtopic: 'Monotonic Stack', name: 'Next Greater Element I', difficulty: 2 },
          { id: 185, subId: 16, subtopic: 'Monotonic Stack', name: 'Next Smaller Element / Help Classmates', difficulty: 3 },
          { id: 186, subId: 17, subtopic: 'Monotonic Stack', name: 'Next Greater Element II (Circular Array)', difficulty: 3 },
          { id: 187, subId: 18, subtopic: 'Monotonic Stack', name: 'Stock Span Problem', difficulty: 3 },
          { id: 188, subId: 19, subtopic: 'Monotonic Stack', name: 'Number of Greater Elements to the Right', difficulty: 3 },
          { id: 189, subId: 20, subtopic: 'Monotonic Stack', name: 'Asteroid Collision', difficulty: 3 },
          { id: 190, subId: 21, subtopic: 'Monotonic Stack', name: 'Remove K Digits', difficulty: 4 },
          { id: 191, subId: 22, subtopic: 'Monotonic Stack', name: 'Remove Duplicate Letters', difficulty: 4 },
          { id: 192, subId: 23, subtopic: 'Advanced Monotonic', name: 'Largest Rectangle in Histogram', difficulty: 4 },
          { id: 193, subId: 24, subtopic: 'Advanced Monotonic', name: 'Sum of Subarray Minimums', difficulty: 4 },
          { id: 194, subId: 25, subtopic: 'Advanced Monotonic', name: 'Sum of Subarray Ranges', difficulty: 4 },
          { id: 195, subId: 26, subtopic: 'Advanced Monotonic', name: 'Maximal Rectangle (2D Grid)', difficulty: 5 },
          { id: 196, subId: 27, subtopic: 'Design', name: 'Min Stack (O(1) getMin)', difficulty: 3 },
          { id: 197, subId: 28, subtopic: 'Design', name: 'The Celebrity Problem', difficulty: 3 },
        ]
      },
      {
        name: 'Queues',
        slug: 'queues',
        icon: '🔁',
        subtopics: ['Implementation', 'Applications', 'Deque & Sliding Window'],
        questions: [
          { id: 198, subId: 1, subtopic: 'Implementation', name: 'Implement Queue using Arrays', difficulty: 1 },
          { id: 199, subId: 2, subtopic: 'Implementation', name: 'Implement Queue using Linked List', difficulty: 1 },
          { id: 200, subId: 3, subtopic: 'Implementation', name: 'Implement Queue using Stacks', difficulty: 2 },
          { id: 201, subId: 4, subtopic: 'Implementation', name: 'Implement Stack using Queues', difficulty: 2 },
          { id: 202, subId: 5, subtopic: 'Implementation', name: 'Reverse First K elements of Queue', difficulty: 2 },
          { id: 203, subId: 6, subtopic: 'Applications', name: 'Number of Students Unable to Eat Lunch', difficulty: 2 },
          { id: 204, subId: 7, subtopic: 'Applications', name: 'First non-repeating character in a stream', difficulty: 3 },
          { id: 205, subId: 8, subtopic: 'Deque', name: 'Sliding Window Maximum', difficulty: 4 },
          { id: 206, subId: 9, subtopic: 'Deque', name: 'Longest Continuous Subarray With Abs Diff ≤ Limit', difficulty: 4 },
          { id: 207, subId: 10, subtopic: 'Deque', name: 'Constrained Subsequence Sum', difficulty: 5 },
        ]
      },
    ]
  },
  'Phase 6': {
    title: 'Hierarchical Data Structures',
    color: '#ef4444',
    topics: [
      {
        name: 'Binary Trees',
        slug: 'binary-trees',
        icon: '🌳',
        subtopics: ['Traversals & Views', 'Properties', 'Paths & LCA', 'Graph-Like', 'Construction'],
        questions: [
          { id: 208, subId: 1, subtopic: 'Traversals', name: 'Preorder Traversal (Recursive & Iterative)', difficulty: 3 },
          { id: 209, subId: 2, subtopic: 'Traversals', name: 'Inorder Traversal (Recursive & Iterative)', difficulty: 3 },
          { id: 210, subId: 3, subtopic: 'Traversals', name: 'Postorder Traversal (Recursive & Iterative)', difficulty: 3 },
          { id: 211, subId: 4, subtopic: 'Traversals', name: 'Binary Tree Level Order Traversal', difficulty: 4 },
          { id: 212, subId: 5, subtopic: 'Traversals', name: 'Binary Tree Zigzag Level Order Traversal', difficulty: 4 },
          { id: 213, subId: 6, subtopic: 'Traversals', name: 'Left / Right View of Binary Tree', difficulty: 4 },
          { id: 214, subId: 7, subtopic: 'Traversals', name: 'Top / Bottom View of Binary Tree', difficulty: 4 },
          { id: 215, subId: 8, subtopic: 'Traversals', name: 'Boundary Traversal of Binary Tree', difficulty: 4 },
          { id: 216, subId: 9, subtopic: 'Traversals', name: 'Diagonal Traversal of Binary Tree', difficulty: 4 },
          { id: 217, subId: 10, subtopic: 'Traversals', name: 'Vertical Order Traversal of a Binary Tree', difficulty: 5 },
          { id: 218, subId: 11, subtopic: 'Properties', name: 'Maximum Depth of Binary Tree', difficulty: 3 },
          { id: 219, subId: 12, subtopic: 'Properties', name: 'Same Tree', difficulty: 3 },
          { id: 220, subId: 13, subtopic: 'Properties', name: 'Invert Binary Tree', difficulty: 3 },
          { id: 221, subId: 14, subtopic: 'Properties', name: 'Symmetric Tree', difficulty: 4 },
          { id: 222, subId: 15, subtopic: 'Properties', name: 'Maximum Width of Binary Tree', difficulty: 4 },
          { id: 223, subId: 16, subtopic: 'Properties', name: 'Count Complete Tree Nodes', difficulty: 4 },
          { id: 224, subId: 17, subtopic: 'Properties', name: 'Diameter of Binary Tree', difficulty: 5 },
          { id: 225, subId: 18, subtopic: 'Properties', name: 'Balanced Binary Tree', difficulty: 5 },
          { id: 226, subId: 19, subtopic: 'Paths & LCA', name: 'Path Sum I', difficulty: 3 },
          { id: 227, subId: 20, subtopic: 'Paths & LCA', name: 'Path Sum II', difficulty: 4 },
          { id: 228, subId: 21, subtopic: 'Paths & LCA', name: 'Sum Root to Leaf Numbers', difficulty: 4 },
          { id: 229, subId: 22, subtopic: 'Paths & LCA', name: 'Maximum Difference Between Node and Ancestor', difficulty: 4 },
          { id: 230, subId: 23, subtopic: 'Paths & LCA', name: 'Lowest Common Ancestor of a Binary Tree', difficulty: 5 },
          { id: 231, subId: 24, subtopic: 'Paths & LCA', name: 'Binary Tree Maximum Path Sum', difficulty: 5 },
          { id: 232, subId: 25, subtopic: 'Paths & LCA', name: 'Path Sum III', difficulty: 5 },
          { id: 233, subId: 26, subtopic: 'Graph-Like', name: 'Minimum time taken to burn the BT', difficulty: 4 },
          { id: 234, subId: 27, subtopic: 'Graph-Like', name: 'All Nodes Distance K in Binary Tree', difficulty: 5 },
          { id: 235, subId: 28, subtopic: 'Graph-Like', name: 'Step-By-Step Directions From a Binary Tree Node to Another', difficulty: 5 },
          { id: 236, subId: 29, subtopic: 'Construction', name: 'Merge Two Binary Trees', difficulty: 3 },
          { id: 237, subId: 30, subtopic: 'Construction', name: 'Children Sum Property in a Binary Tree', difficulty: 3 },
          { id: 238, subId: 31, subtopic: 'Construction', name: 'Construct Binary Tree from Preorder and Inorder Traversal', difficulty: 5 },
          { id: 239, subId: 32, subtopic: 'Construction', name: 'Construct Binary Tree from Inorder and Postorder Traversal', difficulty: 4 },
          { id: 240, subId: 33, subtopic: 'Construction', name: 'Flatten Binary Tree to Linked List', difficulty: 4 },
          { id: 241, subId: 34, subtopic: 'Construction', name: 'Serialize and Deserialize Binary Tree', difficulty: 5 },
        ]
      },
      {
        name: 'Binary Search Trees',
        slug: 'bst',
        icon: '🔍',
        subtopics: ['Core Properties', 'Modifications', 'Construction & Advanced'],
        questions: [
          { id: 242, subId: 1, subtopic: 'Core', name: 'Search in a Binary Search Tree', difficulty: 2 },
          { id: 243, subId: 2, subtopic: 'Core', name: 'Find Minimum/Maximum in BST', difficulty: 2 },
          { id: 244, subId: 3, subtopic: 'Core', name: 'Insert into a Binary Search Tree', difficulty: 3 },
          { id: 245, subId: 4, subtopic: 'Core', name: 'Floor and Ceil in a BST', difficulty: 3 },
          { id: 246, subId: 5, subtopic: 'Core', name: 'Inorder Successor in BST', difficulty: 4 },
          { id: 247, subId: 6, subtopic: 'Core', name: 'Lowest Common Ancestor of a BST', difficulty: 4 },
          { id: 248, subId: 7, subtopic: 'Core', name: 'Validate Binary Search Tree', difficulty: 5 },
          { id: 249, subId: 8, subtopic: 'Core', name: 'Kth Smallest Element in a BST', difficulty: 5 },
          { id: 250, subId: 9, subtopic: 'Modifications', name: 'Delete Node in a BST', difficulty: 4 },
          { id: 251, subId: 10, subtopic: 'Modifications', name: 'Two Sum IV - Input is a BST', difficulty: 5 },
          { id: 252, subId: 11, subtopic: 'Construction', name: 'Convert Sorted Array to Binary Search Tree', difficulty: 3 },
          { id: 253, subId: 12, subtopic: 'Construction', name: 'Construct BST from Preorder Traversal', difficulty: 4 },
          { id: 254, subId: 13, subtopic: 'Construction', name: 'Balance a Binary Search Tree', difficulty: 4 },
          { id: 255, subId: 14, subtopic: 'Construction', name: 'Merge Two Balanced Binary Search Trees', difficulty: 4 },
          { id: 256, subId: 15, subtopic: 'Construction', name: 'Recover Binary Search Tree', difficulty: 5 },
          { id: 257, subId: 16, subtopic: 'Construction', name: 'Largest BST in a Binary Tree', difficulty: 5 },
        ]
      },
      {
        name: 'Tries',
        slug: 'tries',
        icon: '🌐',
        subtopics: ['Implementation', 'Bitwise Tries'],
        questions: [
          { id: 258, subId: 1, subtopic: 'Implementation', name: 'Implement Trie (Prefix Tree)', difficulty: 4 },
          { id: 259, subId: 2, subtopic: 'Implementation', name: 'Design Add and Search Words Data Structure', difficulty: 4 },
          { id: 260, subId: 3, subtopic: 'Implementation', name: 'Longest Word with All Prefixes', difficulty: 4 },
          { id: 261, subId: 4, subtopic: 'Implementation', name: 'Number of Distinct Substrings in a String', difficulty: 4 },
          { id: 262, subId: 5, subtopic: 'Implementation', name: 'Word Search II', difficulty: 5 },
          { id: 263, subId: 6, subtopic: 'Bitwise', name: 'Maximum XOR of Two Numbers in an Array', difficulty: 5 },
          { id: 264, subId: 7, subtopic: 'Bitwise', name: 'Maximum XOR With an Element From Array', difficulty: 5 },
        ]
      },
    ]
  },
  'Phase 7': {
    title: 'Core Data Structures & Techniques',
    color: '#f97316',
    topics: [
      {
        name: 'Hashmaps',
        slug: 'hashmaps',
        icon: '#️⃣',
        subtopics: ['Fundamentals', 'Intermediate', 'Advanced / Multi Concept'],
        questions: [
          { id: 265, subId: 1, subtopic: 'Fundamentals', name: 'Contains Duplicate', difficulty: 1 },
          { id: 266, subId: 2, subtopic: 'Fundamentals', name: 'Valid Anagram (Hashmap Approach)', difficulty: 1 },
          { id: 267, subId: 3, subtopic: 'Fundamentals', name: 'Unique Number of Occurrences', difficulty: 1 },
          { id: 268, subId: 4, subtopic: 'Fundamentals', name: 'Find distinct elements / Find the Frequency', difficulty: 1 },
          { id: 269, subId: 5, subtopic: 'Fundamentals', name: 'Two Sum', difficulty: 2 },
          { id: 270, subId: 6, subtopic: 'Fundamentals', name: 'Intersection of Two Arrays', difficulty: 2 },
          { id: 271, subId: 7, subtopic: 'Fundamentals', name: 'Count Number of Pairs With Absolute Difference K', difficulty: 2 },
          { id: 272, subId: 8, subtopic: 'Fundamentals', name: 'Design HashMap', difficulty: 3 },
          { id: 273, subId: 9, subtopic: 'Intermediate', name: 'Group Anagrams', difficulty: 3 },
          { id: 274, subId: 10, subtopic: 'Intermediate', name: 'Longest Consecutive Sequence', difficulty: 3 },
          { id: 275, subId: 11, subtopic: 'Intermediate', name: 'Subarray Sum Equals K', difficulty: 3 },
          { id: 276, subId: 12, subtopic: 'Intermediate', name: 'Contiguous Array / Largest subarray with 0 sum', difficulty: 3 },
          { id: 277, subId: 13, subtopic: 'Intermediate', name: 'Count subarrays with given XOR', difficulty: 3 },
          { id: 278, subId: 14, subtopic: 'Intermediate', name: 'Subarray Sums Divisible by K', difficulty: 3 },
          { id: 279, subId: 15, subtopic: 'Intermediate', name: 'Continuous Subarray Sum', difficulty: 3 },
          { id: 280, subId: 16, subtopic: 'Advanced', name: 'Maximum Size Subarray Sum Equals k', difficulty: 3 },
          { id: 281, subId: 17, subtopic: 'Advanced', name: 'Top K Frequent Elements', difficulty: 3 },
          { id: 282, subId: 18, subtopic: 'Advanced', name: 'LRU Cache (Least Recently Used)', difficulty: 4 },
          { id: 283, subId: 19, subtopic: 'Advanced', name: 'LFU Cache (Least Frequently Used)', difficulty: 5 },
        ]
      },
      {
        name: 'Heaps / Priority Queues',
        slug: 'heaps-pq',
        icon: '⛰️',
        subtopics: ['Heap Fundamentals', 'Top-K Pattern', 'Merging', 'Advanced / Two-Heaps'],
        questions: [
          { id: 284, subId: 1, subtopic: 'Fundamentals', name: 'Check if an array represents a min heap', difficulty: 2 },
          { id: 285, subId: 2, subtopic: 'Fundamentals', name: 'Convert Min Heap to Max Heap', difficulty: 2 },
          { id: 286, subId: 3, subtopic: 'Fundamentals', name: 'Implement Min/Max Heap', difficulty: 3 },
          { id: 287, subId: 4, subtopic: 'Top-K', name: 'Last Stone Weight', difficulty: 3 },
          { id: 288, subId: 5, subtopic: 'Top-K', name: 'Kth Largest Element in an Array', difficulty: 4 },
          { id: 289, subId: 6, subtopic: 'Top-K', name: 'K Closest Points to Origin', difficulty: 4 },
          { id: 290, subId: 7, subtopic: 'Top-K', name: 'Sort a K Sorted Array / Nearly Sorted Algorithm', difficulty: 4 },
          { id: 291, subId: 8, subtopic: 'Top-K', name: 'Top K Frequent Elements (Heap Approach)', difficulty: 4 },
          { id: 292, subId: 9, subtopic: 'Merging', name: 'Minimum Cost of Ropes', difficulty: 4 },
          { id: 293, subId: 10, subtopic: 'Merging', name: 'Merge K Sorted Lists', difficulty: 5 },
          { id: 294, subId: 11, subtopic: 'Merging', name: 'Kth Smallest Element in a Sorted Matrix', difficulty: 4 },
          { id: 295, subId: 12, subtopic: 'Advanced', name: 'Task Scheduler', difficulty: 5 },
          { id: 296, subId: 13, subtopic: 'Advanced', name: 'Reorganize String', difficulty: 5 },
          { id: 297, subId: 14, subtopic: 'Advanced', name: 'Minimum Number of Refueling Stops', difficulty: 5 },
          { id: 298, subId: 15, subtopic: 'Advanced', name: 'Find Median from Data Stream', difficulty: 5 },
        ]
      },
      {
        name: 'Prefix Sum',
        slug: 'prefix-sum',
        icon: '➕',
        subtopics: ['1D Prefix Sum', '2D Prefix Sum'],
        questions: [
          { id: 299, subId: 1, subtopic: '1D', name: 'Running Sum of 1D Array', difficulty: 1 },
          { id: 300, subId: 2, subtopic: '1D', name: 'Find the Highest Altitude', difficulty: 2 },
          { id: 301, subId: 3, subtopic: '1D', name: 'Find Pivot Index', difficulty: 2 },
          { id: 302, subId: 4, subtopic: '1D', name: 'Range Sum Query - Immutable', difficulty: 2 },
          { id: 303, subId: 5, subtopic: '1D', name: 'Product of Array Except Self', difficulty: 3 },
          { id: 304, subId: 6, subtopic: '1D', name: 'Corporate Flight Bookings', difficulty: 4 },
          { id: 305, subId: 7, subtopic: '1D', name: 'Trapping Rain Water (Prefix Max / Min)', difficulty: 4 },
          { id: 306, subId: 8, subtopic: '2D', name: 'Range Sum Query 2D - Immutable', difficulty: 3 },
          { id: 307, subId: 9, subtopic: '2D', name: 'Matrix Block Sum', difficulty: 3 },
          { id: 308, subId: 10, subtopic: '2D', name: 'Maximum Sum of a 2D Subgrid of size K x K', difficulty: 4 },
        ]
      },
      {
        name: 'Two Pointers & Sliding Window',
        slug: 'two-pointers',
        icon: '↔️',
        subtopics: ['Two Pointers Basics', 'Fixed Size Sliding Window', 'Variable Size Sliding Window', 'Advanced Sliding Window'],
        questions: [
          { id: 309, subId: 1, subtopic: 'Two Pointers', name: 'Move Zeroes (Two Pointer Intuition)', difficulty: 1 },
          { id: 310, subId: 2, subtopic: 'Two Pointers', name: 'Valid Palindrome (Two Pointers)', difficulty: 1 },
          { id: 311, subId: 3, subtopic: 'Two Pointers', name: 'Two Sum II - Input Array Is Sorted', difficulty: 2 },
          { id: 312, subId: 4, subtopic: 'Two Pointers', name: 'Sort Colors (Dutch National Flag)', difficulty: 2 },
          { id: 313, subId: 5, subtopic: 'Two Pointers', name: 'Container With Most Water', difficulty: 3 },
          { id: 314, subId: 6, subtopic: 'Two Pointers', name: '3Sum', difficulty: 3 },
          { id: 315, subId: 7, subtopic: 'Fixed Window', name: 'Maximum Average Subarray I', difficulty: 2 },
          { id: 316, subId: 8, subtopic: 'Fixed Window', name: 'Max Sum Subarray of size K', difficulty: 2 },
          { id: 317, subId: 9, subtopic: 'Fixed Window', name: 'Number of Sub-arrays of Size K and Average ≥ Threshold', difficulty: 2 },
          { id: 318, subId: 10, subtopic: 'Fixed Window', name: 'Minimum Consecutive Cards to Pick Up', difficulty: 2 },
          { id: 319, subId: 11, subtopic: 'Fixed Window', name: 'Maximum Points You Can Obtain from Cards', difficulty: 3 },
          { id: 320, subId: 12, subtopic: 'Variable Window', name: 'Find All Anagrams in a String', difficulty: 3 },
          { id: 321, subId: 13, subtopic: 'Variable Window', name: 'Permutation in String', difficulty: 3 },
          { id: 322, subId: 14, subtopic: 'Variable Window', name: 'Minimum Size Subarray Sum', difficulty: 3 },
          { id: 323, subId: 15, subtopic: 'Variable Window', name: 'Longest Substring Without Repeating Characters', difficulty: 3 },
          { id: 324, subId: 16, subtopic: 'Variable Window', name: 'Longest Repeating Character Replacement', difficulty: 3 },
          { id: 325, subId: 17, subtopic: 'Variable Window', name: 'Max Consecutive Ones III', difficulty: 3 },
          { id: 326, subId: 18, subtopic: 'Variable Window', name: 'Fruit Into Baskets', difficulty: 3 },
          { id: 327, subId: 19, subtopic: 'Variable Window', name: 'Maximum Erasure Value', difficulty: 3 },
          { id: 328, subId: 20, subtopic: 'Variable Window', name: 'Number of Substrings Containing All Three Characters', difficulty: 3 },
          { id: 329, subId: 21, subtopic: 'Advanced', name: 'Binary Subarrays With Sum', difficulty: 3 },
          { id: 330, subId: 22, subtopic: 'Advanced', name: 'Count Number of Nice Subarrays', difficulty: 3 },
          { id: 331, subId: 23, subtopic: 'Advanced', name: 'Subarrays with K Different Integers', difficulty: 4 },
          { id: 332, subId: 24, subtopic: 'Advanced', name: 'Minimum Window Subsequence', difficulty: 4 },
          { id: 333, subId: 25, subtopic: 'Advanced', name: 'Minimum Window Substring', difficulty: 5 },
        ]
      },
      {
        name: 'Bit Manipulation',
        slug: 'bit-manipulation',
        icon: '🔢',
        subtopics: ['Bit Basics', 'XOR Tricks', 'Bit Counting & Advanced'],
        questions: [
          { id: 334, subId: 1, subtopic: 'Basics', name: 'K-th Bit is Set or Not', difficulty: 1 },
          { id: 335, subId: 2, subtopic: 'Basics', name: 'Check if a Number is Odd or Not', difficulty: 1 },
          { id: 336, subId: 3, subtopic: 'Basics', name: 'Check If Number Power of 2 or Not', difficulty: 2 },
          { id: 337, subId: 4, subtopic: 'Basics', name: 'Number Of Even and Odd Bits', difficulty: 2 },
          { id: 338, subId: 5, subtopic: 'Basics', name: 'Minimum Bit Flips To Convert Number', difficulty: 3 },
          { id: 339, subId: 6, subtopic: 'XOR', name: 'Swap Two Numbers (XOR Trick)', difficulty: 2 },
          { id: 340, subId: 7, subtopic: 'XOR', name: 'Single Number I', difficulty: 2 },
          { id: 341, subId: 8, subtopic: 'XOR', name: 'Is Binary Number Multiple of 3', difficulty: 2 },
          { id: 342, subId: 9, subtopic: 'XOR', name: 'Find the repeating and missing number', difficulty: 3 },
          { id: 343, subId: 10, subtopic: 'XOR', name: 'Single Number II', difficulty: 4 },
          { id: 344, subId: 11, subtopic: 'XOR', name: 'Single Number III', difficulty: 5 },
          { id: 345, subId: 12, subtopic: 'Advanced', name: 'Count Set Bits From 1 to N', difficulty: 4 },
          { id: 346, subId: 13, subtopic: 'Advanced', name: 'Bleak Numbers', difficulty: 4 },
          { id: 347, subId: 14, subtopic: 'Advanced', name: 'Minimum Xor Pair', difficulty: 4 },
          { id: 348, subId: 15, subtopic: 'Advanced', name: 'Divide Two Integers (Bit Shifting)', difficulty: 4 },
        ]
      },
    ]
  },
  'Phase 8': {
    title: 'Standard Algorithms',
    color: '#84cc16',
    topics: [
      {
        name: 'Greedy',
        slug: 'greedy',
        icon: '💰',
        subtopics: ['Basics', 'Intervals & Scheduling', 'Array & Jump', 'Advanced'],
        questions: [
          { id: 349, subId: 1, subtopic: 'Basics', name: 'Assign Cookies', difficulty: 1 },
          { id: 350, subId: 2, subtopic: 'Basics', name: 'Lemonade Change', difficulty: 2 },
          { id: 351, subId: 3, subtopic: 'Basics', name: 'Maximize Sum of Array After K Negations', difficulty: 2 },
          { id: 352, subId: 4, subtopic: 'Basics', name: 'Shortest Job First', difficulty: 2 },
          { id: 353, subId: 5, subtopic: 'Basics', name: 'Activity Selection / N Meetings in One Room', difficulty: 2 },
          { id: 354, subId: 6, subtopic: 'Intervals', name: 'Merge Intervals (Greedy View)', difficulty: 3 },
          { id: 355, subId: 7, subtopic: 'Intervals', name: 'Insert Interval', difficulty: 3 },
          { id: 356, subId: 8, subtopic: 'Intervals', name: 'Non-overlapping Intervals', difficulty: 3 },
          { id: 357, subId: 9, subtopic: 'Intervals', name: 'Minimum Number of Arrows to Burst Balloons', difficulty: 3 },
          { id: 358, subId: 10, subtopic: 'Intervals', name: 'Job Sequencing Problem', difficulty: 3 },
          { id: 359, subId: 11, subtopic: 'Intervals', name: 'Minimum Platforms required for a railway', difficulty: 3 },
          { id: 360, subId: 12, subtopic: 'Intervals', name: 'Maximum Meetings in One Room', difficulty: 3 },
          { id: 361, subId: 13, subtopic: 'Intervals', name: 'Task Scheduler (Greedy Approach)', difficulty: 3 },
          { id: 362, subId: 14, subtopic: 'Jump', name: 'Jump Game', difficulty: 3 },
          { id: 363, subId: 15, subtopic: 'Jump', name: 'Valid Parenthesis String', difficulty: 3 },
          { id: 364, subId: 16, subtopic: 'Jump', name: 'Gas Station', difficulty: 3 },
          { id: 365, subId: 17, subtopic: 'Jump', name: 'Jump Game II', difficulty: 3 },
          { id: 366, subId: 18, subtopic: 'Advanced', name: 'Minimize the Heights II', difficulty: 4 },
          { id: 367, subId: 19, subtopic: 'Advanced', name: 'Candy', difficulty: 4 },
          { id: 368, subId: 20, subtopic: 'Advanced', name: 'Huffman Decoding / Coding', difficulty: 4 },
          { id: 369, subId: 21, subtopic: 'Advanced', name: 'Minimum Number of Taps to Open to Water a Garden', difficulty: 4 },
          { id: 370, subId: 22, subtopic: 'Advanced', name: 'Course Schedule III', difficulty: 5 },
        ]
      },
      {
        name: 'Graphs',
        slug: 'graphs',
        icon: '🕸️',
        subtopics: ['Fundamentals', 'Matrix BFS', 'Cycle Detection', 'Topological Sort', 'Shortest Path', 'MST', 'DSU', 'Advanced'],
        questions: [
          { id: 371, subId: 1, subtopic: 'Fundamentals', name: 'BFS of Graph', difficulty: 1 },
          { id: 372, subId: 2, subtopic: 'Fundamentals', name: 'DFS of Graph', difficulty: 1 },
          { id: 373, subId: 3, subtopic: 'Fundamentals', name: 'Find if Path Exists in Graph', difficulty: 2 },
          { id: 374, subId: 4, subtopic: 'Fundamentals', name: 'Number of Provinces', difficulty: 2 },
          { id: 375, subId: 5, subtopic: 'Fundamentals', name: 'Clone Graph', difficulty: 3 },
          { id: 376, subId: 6, subtopic: 'Fundamentals', name: 'Is Graph Bipartite?', difficulty: 3 },
          { id: 377, subId: 7, subtopic: 'Matrix BFS', name: 'Flood Fill', difficulty: 2 },
          { id: 378, subId: 8, subtopic: 'Matrix BFS', name: 'Max Area of Island', difficulty: 2 },
          { id: 379, subId: 9, subtopic: 'Matrix BFS', name: 'Number of Islands', difficulty: 3 },
          { id: 380, subId: 10, subtopic: 'Matrix BFS', name: 'Rotting Oranges', difficulty: 3 },
          { id: 381, subId: 11, subtopic: 'Matrix BFS', name: '01 Matrix / Distance of nearest cell having 1', difficulty: 3 },
          { id: 382, subId: 12, subtopic: 'Matrix BFS', name: 'Surrounded Regions', difficulty: 3 },
          { id: 383, subId: 13, subtopic: 'Matrix BFS', name: 'Number of Enclaves', difficulty: 3 },
          { id: 384, subId: 14, subtopic: 'Matrix BFS', name: 'Shortest Path in Binary Matrix', difficulty: 3 },
          { id: 385, subId: 15, subtopic: 'Matrix BFS', name: 'Swim in Rising Water', difficulty: 4 },
          { id: 386, subId: 16, subtopic: 'Matrix BFS', name: 'Making A Large Island', difficulty: 4 },
          { id: 387, subId: 17, subtopic: 'Cycle Detection', name: 'Cycle Detection in Undirected Graph', difficulty: 2 },
          { id: 388, subId: 18, subtopic: 'Cycle Detection', name: 'Detect Cycle in a Directed Graph', difficulty: 3 },
          { id: 389, subId: 19, subtopic: 'Cycle Detection', name: 'Find Eventual Safe States', difficulty: 3 },
          { id: 390, subId: 20, subtopic: 'Topological Sort', name: 'Topological Sort', difficulty: 2 },
          { id: 391, subId: 21, subtopic: 'Topological Sort', name: 'Course Schedule', difficulty: 3 },
          { id: 392, subId: 22, subtopic: 'Topological Sort', name: 'Course Schedule II', difficulty: 3 },
          { id: 393, subId: 23, subtopic: 'Topological Sort', name: 'Alien Dictionary', difficulty: 4 },
          { id: 394, subId: 24, subtopic: 'Topological Sort', name: 'Parallel Courses III', difficulty: 4 },
          { id: 395, subId: 25, subtopic: 'Shortest Path', name: 'Shortest Path in Undirected Graph (Unit Weights)', difficulty: 2 },
          { id: 396, subId: 26, subtopic: 'Shortest Path', name: 'Shortest Path in DAG', difficulty: 2 },
          { id: 397, subId: 27, subtopic: 'Shortest Path', name: "Dijkstra's Algorithm", difficulty: 3 },
          { id: 398, subId: 28, subtopic: 'Shortest Path', name: 'Network Delay Time', difficulty: 3 },
          { id: 399, subId: 29, subtopic: 'Shortest Path', name: 'Path With Minimum Effort', difficulty: 3 },
          { id: 400, subId: 30, subtopic: 'Shortest Path', name: 'Cheapest Flights Within K Stops', difficulty: 3 },
          { id: 401, subId: 31, subtopic: 'Shortest Path', name: 'Path with Maximum Probability', difficulty: 3 },
          { id: 402, subId: 32, subtopic: 'Shortest Path', name: 'Bellman-Ford Algorithm', difficulty: 3 },
          { id: 403, subId: 33, subtopic: 'Shortest Path', name: 'Floyd Warshall Algorithm', difficulty: 3 },
          { id: 404, subId: 34, subtopic: 'Shortest Path', name: 'Find the City With the Smallest Number of Neighbors', difficulty: 3 },
          { id: 405, subId: 35, subtopic: 'Shortest Path', name: 'Minimum Multiplications to Reach End', difficulty: 3 },
          { id: 406, subId: 36, subtopic: 'Shortest Path', name: 'Number of Ways to Arrive at Destination', difficulty: 3 },
          { id: 407, subId: 37, subtopic: 'MST', name: 'Minimum Spanning Tree', difficulty: 2 },
          { id: 408, subId: 38, subtopic: 'MST', name: "Prim's Algorithm", difficulty: 3 },
          { id: 409, subId: 39, subtopic: 'MST', name: 'Min Cost to Connect All Points (Kruskal)', difficulty: 3 },
          { id: 410, subId: 40, subtopic: 'DSU', name: 'Disjoint Set', difficulty: 2 },
          { id: 411, subId: 41, subtopic: 'DSU', name: 'Number of Operations to Make Network Connected', difficulty: 3 },
          { id: 412, subId: 42, subtopic: 'DSU', name: 'Accounts Merge', difficulty: 3 },
          { id: 413, subId: 43, subtopic: 'DSU', name: 'Most Stones Removed with Same Row or Column', difficulty: 3 },
          { id: 414, subId: 44, subtopic: 'DSU', name: 'Redundant Connection', difficulty: 3 },
          { id: 415, subId: 45, subtopic: 'DSU', name: 'Evaluate Division', difficulty: 4 },
          { id: 416, subId: 46, subtopic: 'DSU', name: 'Number of Islands II', difficulty: 4 },
          { id: 417, subId: 47, subtopic: 'Advanced', name: "Kosaraju's Algorithm", difficulty: 4 },
          { id: 418, subId: 48, subtopic: 'Advanced', name: "Tarjan's Algorithm / Bridges in Graph", difficulty: 4 },
          { id: 419, subId: 49, subtopic: 'Advanced', name: 'Articulation Point in Graph', difficulty: 4 },
          { id: 420, subId: 50, subtopic: 'Advanced', name: 'Critical Connections in a Network', difficulty: 4 },
          { id: 421, subId: 51, subtopic: 'Advanced', name: 'Snake and Ladder Problem', difficulty: 3 },
          { id: 422, subId: 52, subtopic: 'Advanced', name: 'Word Ladder', difficulty: 4 },
          { id: 423, subId: 53, subtopic: 'Advanced', name: 'Reorder Routes to Make All Paths Lead to the City Zero', difficulty: 4 },
          { id: 424, subId: 54, subtopic: 'Advanced', name: 'Word Ladder II', difficulty: 5 },
          { id: 425, subId: 55, subtopic: 'Advanced', name: 'Escape the Spreading Fire', difficulty: 5 },
        ]
      },
    ]
  },
  'Phase 9': {
    title: 'Exhaustive Search & Optimisation',
    color: '#ec4899',
    topics: [
      {
        name: 'Backtracking',
        slug: 'backtracking',
        icon: '↩️',
        subtopics: ['Subsequence & Subset', 'Combinations', 'Permutations', 'String Backtracking', 'Grid & Maze'],
        questions: [
          { id: 426, subId: 1, subtopic: 'Subsequence', name: 'Check if subsequence with sum K Exists', difficulty: 2 },
          { id: 427, subId: 2, subtopic: 'Subsequence', name: 'Count all subsequences with sum K', difficulty: 2 },
          { id: 428, subId: 3, subtopic: 'Subsequence', name: 'Subsets / Power Set', difficulty: 3 },
          { id: 429, subId: 4, subtopic: 'Subsequence', name: 'Subsets II (With Duplicates)', difficulty: 3 },
          { id: 430, subId: 5, subtopic: 'Subsequence', name: 'Subset Sums', difficulty: 3 },
          { id: 431, subId: 6, subtopic: 'Combinations', name: 'Combination Sum I', difficulty: 3 },
          { id: 432, subId: 7, subtopic: 'Combinations', name: 'Combination Sum II', difficulty: 3 },
          { id: 433, subId: 8, subtopic: 'Combinations', name: 'Combination Sum III', difficulty: 3 },
          { id: 434, subId: 9, subtopic: 'Combinations', name: 'N Digit numbers with digits in increasing order', difficulty: 3 },
          { id: 435, subId: 10, subtopic: 'Permutations', name: 'Permutations II (With Duplicates)', difficulty: 3 },
          { id: 436, subId: 11, subtopic: 'Permutations', name: 'Letter Combinations of a Phone Number', difficulty: 3 },
          { id: 437, subId: 12, subtopic: 'Permutations', name: 'Generate Parentheses', difficulty: 3 },
          { id: 438, subId: 13, subtopic: 'String', name: 'Palindrome Partitioning', difficulty: 4 },
          { id: 439, subId: 14, subtopic: 'String', name: 'Word Break', difficulty: 4 },
          { id: 440, subId: 15, subtopic: 'String', name: 'Remove Invalid Parentheses', difficulty: 5 },
          { id: 441, subId: 16, subtopic: 'String', name: 'Expression Add Operators', difficulty: 5 },
          { id: 442, subId: 17, subtopic: 'Grid', name: 'Rat in a Maze', difficulty: 4 },
          { id: 443, subId: 18, subtopic: 'Grid', name: 'Word Search', difficulty: 4 },
          { id: 444, subId: 19, subtopic: 'Grid', name: 'M-Coloring Problem', difficulty: 4 },
          { id: 445, subId: 20, subtopic: 'Grid', name: 'N-Queens', difficulty: 5 },
          { id: 446, subId: 21, subtopic: 'Grid', name: 'N-Queens II', difficulty: 5 },
          { id: 447, subId: 22, subtopic: 'Grid', name: 'Sudoku Solver', difficulty: 5 },
        ]
      },
      {
        name: 'Dynamic Programming',
        slug: 'dynamic-programming',
        icon: '🧩',
        subtopics: ['1D DP', '2D Grids & Paths', '0/1 Knapsack', 'Unbounded Knapsack', 'DP on Strings', 'DP on Stocks', 'LIS', 'Partition DP & MCM'],
        questions: [
          { id: 448, subId: 1, subtopic: '1D DP', name: 'Fibonacci Number', difficulty: 1 },
          { id: 449, subId: 2, subtopic: '1D DP', name: 'Climbing Stairs', difficulty: 1 },
          { id: 450, subId: 3, subtopic: '1D DP', name: 'Min Cost Climbing Stairs', difficulty: 2 },
          { id: 451, subId: 4, subtopic: '1D DP', name: 'Frog Jump', difficulty: 2 },
          { id: 452, subId: 5, subtopic: '1D DP', name: 'Frog Jump with K Distances', difficulty: 2 },
          { id: 453, subId: 6, subtopic: '1D DP', name: 'House Robber', difficulty: 2 },
          { id: 454, subId: 7, subtopic: '1D DP', name: 'House Robber II', difficulty: 3 },
          { id: 455, subId: 8, subtopic: '1D DP', name: 'Decode Ways', difficulty: 3 },
          { id: 456, subId: 9, subtopic: '2D Grids', name: 'Unique Paths', difficulty: 2 },
          { id: 457, subId: 10, subtopic: '2D Grids', name: 'Unique Paths II', difficulty: 3 },
          { id: 458, subId: 11, subtopic: '2D Grids', name: 'Minimum Path Sum', difficulty: 3 },
          { id: 459, subId: 12, subtopic: '2D Grids', name: 'Triangle', difficulty: 3 },
          { id: 460, subId: 13, subtopic: '2D Grids', name: 'Minimum Falling Path Sum', difficulty: 3 },
          { id: 461, subId: 14, subtopic: '2D Grids', name: 'Dungeon Game', difficulty: 4 },
          { id: 462, subId: 15, subtopic: '2D Grids', name: 'Cherry Pickup II / Ninja and his Friends', difficulty: 4 },
          { id: 463, subId: 16, subtopic: '0/1 Knapsack', name: 'Subset Sum Problem', difficulty: 2 },
          { id: 464, subId: 17, subtopic: '0/1 Knapsack', name: 'Partition Equal Subset Sum', difficulty: 3 },
          { id: 465, subId: 18, subtopic: '0/1 Knapsack', name: 'Count Subsets with Sum K', difficulty: 3 },
          { id: 466, subId: 19, subtopic: '0/1 Knapsack', name: 'Target Sum', difficulty: 3 },
          { id: 467, subId: 20, subtopic: '0/1 Knapsack', name: 'Count Partitions with Given Difference', difficulty: 3 },
          { id: 468, subId: 21, subtopic: '0/1 Knapsack', name: '0/1 Knapsack Problem', difficulty: 3 },
          { id: 469, subId: 22, subtopic: '0/1 Knapsack', name: 'Partition Array Into Two Arrays to Minimize Sum Difference', difficulty: 4 },
          { id: 470, subId: 23, subtopic: '0/1 Knapsack', name: 'Last Stone Weight II', difficulty: 4 },
          { id: 471, subId: 24, subtopic: 'Unbounded Knapsack', name: 'Rod Cutting Problem', difficulty: 3 },
          { id: 472, subId: 25, subtopic: 'Unbounded Knapsack', name: 'Coin Change', difficulty: 3 },
          { id: 473, subId: 26, subtopic: 'Unbounded Knapsack', name: 'Coin Change II', difficulty: 3 },
          { id: 474, subId: 27, subtopic: 'Unbounded Knapsack', name: 'Perfect Squares', difficulty: 3 },
          { id: 475, subId: 28, subtopic: 'DP on Strings', name: 'Longest Common Subsequence', difficulty: 3 },
          { id: 476, subId: 29, subtopic: 'DP on Strings', name: 'Print Longest Common Subsequence', difficulty: 3 },
          { id: 477, subId: 30, subtopic: 'DP on Strings', name: 'Longest Common Substring', difficulty: 3 },
          { id: 478, subId: 31, subtopic: 'DP on Strings', name: 'Longest Palindromic Subsequence', difficulty: 3 },
          { id: 479, subId: 32, subtopic: 'DP on Strings', name: 'Minimum Insertions to Make String Palindrome', difficulty: 3 },
          { id: 480, subId: 33, subtopic: 'DP on Strings', name: 'Delete Operation for Two Strings', difficulty: 3 },
          { id: 481, subId: 34, subtopic: 'DP on Strings', name: 'Shortest Common Supersequence', difficulty: 4 },
          { id: 482, subId: 35, subtopic: 'DP on Strings', name: 'Distinct Subsequences', difficulty: 4 },
          { id: 483, subId: 36, subtopic: 'DP on Strings', name: 'Edit Distance', difficulty: 4 },
          { id: 484, subId: 37, subtopic: 'DP on Strings', name: 'Wildcard Matching', difficulty: 4 },
          { id: 485, subId: 38, subtopic: 'DP on Strings', name: 'Regular Expression Matching', difficulty: 5 },
          { id: 486, subId: 39, subtopic: 'DP on Stocks', name: 'Best Time to Buy and Sell Stock', difficulty: 1 },
          { id: 487, subId: 40, subtopic: 'DP on Stocks', name: 'Best Time to Buy and Sell Stock II', difficulty: 2 },
          { id: 488, subId: 41, subtopic: 'DP on Stocks', name: 'Best Time to Buy and Sell Stock with Cooldown', difficulty: 2 },
          { id: 489, subId: 42, subtopic: 'DP on Stocks', name: 'Best Time to Buy and Sell Stock with Transaction Fee', difficulty: 3 },
          { id: 490, subId: 43, subtopic: 'DP on Stocks', name: 'Best Time to Buy and Sell Stock III', difficulty: 4 },
          { id: 491, subId: 44, subtopic: 'DP on Stocks', name: 'Best Time to Buy and Sell Stock IV', difficulty: 4 },
          { id: 492, subId: 45, subtopic: 'LIS', name: 'Longest Increasing Subsequence', difficulty: 3 },
          { id: 493, subId: 46, subtopic: 'LIS', name: 'Print Longest Increasing Subsequence', difficulty: 3 },
          { id: 494, subId: 47, subtopic: 'LIS', name: 'Largest Divisible Subset', difficulty: 3 },
          { id: 495, subId: 48, subtopic: 'LIS', name: 'Longest String Chain', difficulty: 3 },
          { id: 496, subId: 49, subtopic: 'LIS', name: 'Longest Bitonic Subsequence', difficulty: 4 },
          { id: 497, subId: 50, subtopic: 'LIS', name: 'Number of Longest Increasing Subsequences', difficulty: 4 },
          { id: 498, subId: 51, subtopic: 'LIS', name: 'Russian Doll Envelopes', difficulty: 5 },
          { id: 499, subId: 52, subtopic: 'Partition DP', name: 'Matrix Chain Multiplication', difficulty: 4 },
          { id: 500, subId: 53, subtopic: 'Partition DP', name: 'Minimum Cost to Cut a Stick', difficulty: 4 },
          { id: 501, subId: 54, subtopic: 'Partition DP', name: 'Burst Balloons', difficulty: 5 },
          { id: 502, subId: 55, subtopic: 'Partition DP', name: 'Palindrome Partitioning II', difficulty: 5 },
        ]
      },
    ]
  },
}
