// lib/lc-links.ts — Real LeetCode & GFG links for all problems

export const PROBLEM_LINKS: Record<string, { lc?: string; gfg?: string }> = {
  // ── ARRAYS ──
  'Find Element at a Given Index': { gfg: 'https://practice.geeksforgeeks.org/problems/access-the-element/1' },
  'Min and Max in Array': { gfg: 'https://practice.geeksforgeeks.org/problems/find-minimum-and-maximum-element-in-an-array4428/1' },
  'Sum of Array': { gfg: 'https://practice.geeksforgeeks.org/problems/sum-of-array-elements2502/1' },
  'Sum of Digits': { gfg: 'https://practice.geeksforgeeks.org/problems/sum-of-digits1742/1' },
  'Check If Array is Sorted': { lc: 'https://leetcode.com/problems/check-if-array-is-sorted-and-rotated/', gfg: 'https://practice.geeksforgeeks.org/problems/check-if-an-array-is-sorted0701/1' },
  'Alternates In Array': { gfg: 'https://practice.geeksforgeeks.org/problems/check-if-two-arrays-are-equal-or-not3847/1' },
  'Remove Duplicates from Array': { lc: 'https://leetcode.com/problems/remove-duplicates-from-sorted-array/' },
  'Second Largest in Array': { lc: 'https://leetcode.com/problems/second-largest-digit-in-a-string/', gfg: 'https://practice.geeksforgeeks.org/problems/second-largest3735/1' },
  'Reverse an Array': { lc: 'https://leetcode.com/problems/reverse-string/', gfg: 'https://practice.geeksforgeeks.org/problems/reverse-an-array/0' },
  'Missing Number': { lc: 'https://leetcode.com/problems/missing-number/' },
  'Segregate 0s and 1s': { gfg: 'https://practice.geeksforgeeks.org/problems/segregate-0s-and-1s5106/1' },
  'Maximum Consecutive Ones': { lc: 'https://leetcode.com/problems/max-consecutive-ones/' },
  'Palindromic Array': { gfg: 'https://practice.geeksforgeeks.org/problems/palindromic-array3700/1' },
  'Move Zeroes to End': { lc: 'https://leetcode.com/problems/move-zeroes/' },
  'Sort array with 0s 1s and 2s (Dutch Flag)': { lc: 'https://leetcode.com/problems/sort-colors/', gfg: 'https://practice.geeksforgeeks.org/problems/sort-an-array-of-0s-1s-and-2s4231/1' },
  'Equilibrium Point': { lc: 'https://leetcode.com/problems/find-pivot-index/', gfg: 'https://practice.geeksforgeeks.org/problems/equilibrium-point-1587115620/1' },
  'Reverse Integer': { lc: 'https://leetcode.com/problems/reverse-integer/' },
  'Leaders in Array': { gfg: 'https://practice.geeksforgeeks.org/problems/leaders-in-an-array-1587115620/1' },
  'Increasing Array': { gfg: 'https://practice.geeksforgeeks.org/problems/make-array-elements-unique/1' },
  'Rearrange Array Elements by Sign': { lc: 'https://leetcode.com/problems/rearrange-array-elements-by-sign/' },
  'Rotate Array by One': { gfg: 'https://practice.geeksforgeeks.org/problems/cyclically-rotate-an-array-by-one2614/1' },
  'Majority Element I (Boyer-Moore)': { lc: 'https://leetcode.com/problems/majority-element/' },
  'Rotate Array by K steps': { lc: 'https://leetcode.com/problems/rotate-array/' },
  'Wiggle Sort II': { lc: 'https://leetcode.com/problems/wiggle-sort-ii/' },
  'Majority Element II': { lc: 'https://leetcode.com/problems/majority-element-ii/' },
  'Best Time to Buy and Sell Stock': { lc: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/' },
  'Next Permutation': { lc: 'https://leetcode.com/problems/next-permutation/' },
  'Maximum Value Of Expression': { lc: 'https://leetcode.com/problems/maximum-value-of-an-ordered-triplet-i/' },
  'First Missing Positive': { lc: 'https://leetcode.com/problems/first-missing-positive/' },

  // ── 2D ARRAYS ──
  'Sum of elements in a matrix': { gfg: 'https://practice.geeksforgeeks.org/problems/sum-of-all-elements-of-a-matrix-1587115621/1' },
  'Count Number Of Zeroes': { gfg: 'https://practice.geeksforgeeks.org/problems/count-zeros-in-a-sorted-matrix1941/1' },
  'Count Negative Numbers in a matrix': { lc: 'https://leetcode.com/problems/count-negative-numbers-in-a-sorted-matrix/' },
  'Matrix Diagonal Sum': { lc: 'https://leetcode.com/problems/matrix-diagonal-sum/' },
  'Addition of Two Square Matrix': { gfg: 'https://practice.geeksforgeeks.org/problems/addition-of-two-matrices/0' },
  'Multiply Matrices': { gfg: 'https://practice.geeksforgeeks.org/problems/multiply-matrices/1' },
  'Transpose Matrix': { lc: 'https://leetcode.com/problems/transpose-matrix/' },
  'Spiral Matrix': { lc: 'https://leetcode.com/problems/spiral-matrix/' },
  'ZigZag Matrix': { gfg: 'https://practice.geeksforgeeks.org/problems/zigzag-traversal-of-matrix/1' },
  'Rotate Matrix (90°)': { lc: 'https://leetcode.com/problems/rotate-image/' },
  'Determine Whether matrix can be obtained by rotation': { lc: 'https://leetcode.com/problems/determine-whether-matrix-can-be-obtained-by-rotation/' },
  'Set Matrix Zeroes': { lc: 'https://leetcode.com/problems/set-matrix-zeroes/' },

  // ── BASIC MATHS ──
  'Check if a number is Armstrong': { gfg: 'https://practice.geeksforgeeks.org/problems/armstrong-numbers2727/1' },
  'Print all Divisors of a Number': { gfg: 'https://practice.geeksforgeeks.org/problems/sum-of-all-divisors-from-1-to-n4738/1' },
  'Check if a number is Prime': { gfg: 'https://practice.geeksforgeeks.org/problems/prime-number2314/1' },
  'GCD / HCF of 2 numbers': { lc: 'https://leetcode.com/problems/find-greatest-common-divisor-of-array/' },
  'Prime Factorisation of a Number': { gfg: 'https://practice.geeksforgeeks.org/problems/prime-factors5052/1' },
  'Count Primes in range L to R': { lc: 'https://leetcode.com/problems/count-primes/' },

  // ── STRINGS ──
  'Maximum Occuring Character': { gfg: 'https://practice.geeksforgeeks.org/problems/maximum-occuring-character-1587115620/1' },
  'Remove Spaces': { gfg: 'https://practice.geeksforgeeks.org/problems/remove-spaces0128/1' },
  'Print first letter of every word': { gfg: 'https://practice.geeksforgeeks.org/problems/print-first-letter-of-every-word-in-the-string/0' },
  'Remove Consecutive Characters': { gfg: 'https://practice.geeksforgeeks.org/problems/consecutive-elements3838/1' },
  'Valid Palindrome': { lc: 'https://leetcode.com/problems/valid-palindrome/' },
  'Valid Anagram': { lc: 'https://leetcode.com/problems/valid-anagram/' },
  'Isomorphic Strings': { lc: 'https://leetcode.com/problems/isomorphic-strings/' },
  'Delete Characters To Make Fancy String': { lc: 'https://leetcode.com/problems/delete-characters-to-make-fancy-string/' },
  'Reverse Words in a String': { lc: 'https://leetcode.com/problems/reverse-words-in-a-string/' },
  'String to integer (atoi)': { lc: 'https://leetcode.com/problems/string-to-integer-atoi/' },
  'Roman to integer': { lc: 'https://leetcode.com/problems/roman-to-integer/' },
  'Rotate String': { lc: 'https://leetcode.com/problems/rotate-string/' },
  'Longest common prefix': { lc: 'https://leetcode.com/problems/longest-common-prefix/' },
  'Longest palindromic substring': { lc: 'https://leetcode.com/problems/longest-palindromic-substring/' },
  'Multiply Two Strings': { lc: 'https://leetcode.com/problems/multiply-strings/' },
  'Maximum Nesting Depth of the Parentheses': { lc: 'https://leetcode.com/problems/maximum-nesting-depth-of-the-parentheses/' },
  'Beauty Of All substrings': { lc: 'https://leetcode.com/problems/sum-of-beauty-of-all-substrings/' },

  // ── BINARY SEARCH ──
  'Search X in sorted array': { lc: 'https://leetcode.com/problems/binary-search/' },
  'Lower Bound': { gfg: 'https://practice.geeksforgeeks.org/problems/implement-lower-bound/1' },
  'Upper Bound': { gfg: 'https://practice.geeksforgeeks.org/problems/implement-upper-bound/1' },
  'Search insert position': { lc: 'https://leetcode.com/problems/search-insert-position/' },
  'Floor In Sorted Array': { gfg: 'https://practice.geeksforgeeks.org/problems/floor-in-a-sorted-array-1587115620/1' },
  'Ceil In Sorted Array': { gfg: 'https://practice.geeksforgeeks.org/problems/ceil-the-floor2802/1' },
  'Guess Number Higher or Lower API': { lc: 'https://leetcode.com/problems/guess-number-higher-or-lower/' },
  'First 1 in a Sorted Binary Array': { gfg: 'https://practice.geeksforgeeks.org/problems/index-of-an-extra-element/1' },
  'Kth Missing Positive Number': { lc: 'https://leetcode.com/problems/kth-missing-positive-number/' },
  'Find minimum in Rotated Sorted Array': { lc: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/' },
  'First and last occurrence': { lc: 'https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/' },
  'Search in rotated sorted array-I': { lc: 'https://leetcode.com/problems/search-in-rotated-sorted-array/' },
  'Search in rotated sorted array-II': { lc: 'https://leetcode.com/problems/search-in-rotated-sorted-array-ii/' },
  'Single element in a Sorted Array': { lc: 'https://leetcode.com/problems/single-element-in-a-sorted-array/' },
  'Find kth Rotation': { gfg: 'https://practice.geeksforgeeks.org/problems/rotation4723/1' },
  'Find Peak Element': { lc: 'https://leetcode.com/problems/find-peak-element/' },
  'Count Negative Numbers in a Sorted Matrix': { lc: 'https://leetcode.com/problems/count-negative-numbers-in-a-sorted-matrix/' },
  'Find row with maximum 1s': { gfg: 'https://practice.geeksforgeeks.org/problems/row-with-max-1s0023/1' },
  'Search a 2D Matrix I': { lc: 'https://leetcode.com/problems/search-a-2d-matrix/' },
  'Search a 2D Matrix  II': { lc: 'https://leetcode.com/problems/search-a-2d-matrix-ii/' },
  'Find Peak Element - II': { lc: 'https://leetcode.com/problems/find-a-peak-element-ii/' },
  'Median in a row-wise sorted Matrix': { gfg: 'https://practice.geeksforgeeks.org/problems/median-in-a-row-wise-sorted-matrix1527/1' },
  'Sqrt (x)': { lc: 'https://leetcode.com/problems/sqrtx/' },
  'Valid Perfect Square': { lc: 'https://leetcode.com/problems/valid-perfect-square/' },
  'Find Nth root of a number': { gfg: 'https://practice.geeksforgeeks.org/problems/find-nth-root-of-m3828/1' },
  'Koko eating bananas': { lc: 'https://leetcode.com/problems/koko-eating-bananas/' },
  'Find the Smallest Divisor Given a Threshold': { lc: 'https://leetcode.com/problems/find-the-smallest-divisor-given-a-threshold/' },
  'Minimum Speed to Arrive on Time': { lc: 'https://leetcode.com/problems/minimum-speed-to-arrive-on-time/' },
  'Minimum days to make M bouquets': { lc: 'https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/' },
  'Capacity to Ship Packages Within D Days': { lc: 'https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/' },
  'Book Allocation Problem': { gfg: 'https://practice.geeksforgeeks.org/problems/allocate-minimum-number-of-pages0937/1' },
  'Split Array Largest Sum': { lc: 'https://leetcode.com/problems/split-array-largest-sum/' },
  "Painter's Partition Problem": { gfg: 'https://practice.geeksforgeeks.org/problems/the-painters-partition-problem1535/1' },
  'K-th element of two sorted Arrays': { gfg: 'https://practice.geeksforgeeks.org/problems/k-th-element-of-two-sorted-array1317/1' },
  'Aggressive Cows': { gfg: 'https://practice.geeksforgeeks.org/problems/aggressive-cows/0' },
  'Minimize Max Distance to Gas Station': { lc: 'https://leetcode.com/problems/minimize-max-distance-to-gas-station/' },
  'Median of Two Sorted Arrays': { lc: 'https://leetcode.com/problems/median-of-two-sorted-arrays/' },

  // ── RECURSION ──
  'Print 1 to N without using loops': { gfg: 'https://practice.geeksforgeeks.org/problems/print-1-to-n-without-using-loops-1587115620/1' },
  'Print N to 1 without loop': { gfg: 'https://practice.geeksforgeeks.org/problems/print-n-to-1-without-loop/1' },
  'Sum of first N numbers': { gfg: 'https://practice.geeksforgeeks.org/problems/sum-of-first-n-terms5843/1' },
  'Factorial of a given number': { gfg: 'https://practice.geeksforgeeks.org/problems/find-all-factorial-numbers-less-than-or-equal-to-n3548/1' },
  'Fibonacci Number': { lc: 'https://leetcode.com/problems/fibonacci-number/' },
  'Pow(x, n)': { lc: 'https://leetcode.com/problems/powx-n/' },
  'Count Good Numbers': { lc: 'https://leetcode.com/problems/count-good-numbers/' },
  'Generate Binary Strings Without Consecutive 1s': { lc: 'https://leetcode.com/problems/count-the-number-of-good-subarrays/' },

  // ── SORTING ──
  'Linear Search': { gfg: 'https://practice.geeksforgeeks.org/problems/who-will-win-1587115621/1' },
  'Sort An Array (Implement Merge / Quick Sort)': { lc: 'https://leetcode.com/problems/sort-an-array/' },
  'Sort Array By Parity': { lc: 'https://leetcode.com/problems/sort-array-by-parity/' },
  'Maximum Gap': { lc: 'https://leetcode.com/problems/maximum-gap/' },
  'Sort Elements by Decreasing Frequency': { lc: 'https://leetcode.com/problems/sort-array-by-increasing-frequency/' },
  'Reorder Data In Log Files': { lc: 'https://leetcode.com/problems/reorder-data-in-log-files/' },
  'Merge Intervals': { lc: 'https://leetcode.com/problems/merge-intervals/' },
  'Count Inversions (Merge Sort)': { gfg: 'https://practice.geeksforgeeks.org/problems/inversion-of-array-1587115620/1' },
  'Reverse Pairs (Merge Sort)': { lc: 'https://leetcode.com/problems/reverse-pairs/' },

  // ── LINKED LIST ──
  'Array to Linked List': { gfg: 'https://practice.geeksforgeeks.org/problems/introduction-to-linked-list/1' },
  'Count Nodes / Find Length of Linked List': { gfg: 'https://practice.geeksforgeeks.org/problems/count-nodes-of-linked-list/0' },
  'Search in a Linked List': { gfg: 'https://practice.geeksforgeeks.org/problems/search-in-linked-list-1664434193/1' },
  'Insert Node at Head / Tail': { gfg: 'https://practice.geeksforgeeks.org/problems/linked-list-insertion-1587115620/1' },
  'Remove Linked List Elements (By Value)': { lc: 'https://leetcode.com/problems/remove-linked-list-elements/' },
  'Remove Duplicates from Sorted List': { lc: 'https://leetcode.com/problems/remove-duplicates-from-sorted-list/' },
  'Delete Node in a Linked List (Given only node ref)': { lc: 'https://leetcode.com/problems/delete-node-in-a-linked-list/' },
  'Remove Duplicates from Unsorted List': { lc: 'https://leetcode.com/problems/remove-duplicates-from-an-unsorted-linked-list/' },
  'Delete the Middle Node of a Linked List': { lc: 'https://leetcode.com/problems/delete-the-middle-node-of-a-linked-list/' },
  'Middle of the Linked List': { lc: 'https://leetcode.com/problems/middle-of-the-linked-list/' },
  'Linked List Cycle': { lc: 'https://leetcode.com/problems/linked-list-cycle/' },
  'Intersection of Two Linked Lists': { lc: 'https://leetcode.com/problems/intersection-of-two-linked-lists/' },
  'Length of Loop in Linked List': { gfg: 'https://practice.geeksforgeeks.org/problems/find-length-of-loop/1' },
  'Linked List Cycle II (Find Starting Point)': { lc: 'https://leetcode.com/problems/linked-list-cycle-ii/' },
  'Remove Loop in Linked List': { gfg: 'https://practice.geeksforgeeks.org/problems/remove-loop-in-linked-list/1' },
  'Remove Nth Node From End of List': { lc: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/' },
  'Reverse a Linked List (Iterative & Recursive)': { lc: 'https://leetcode.com/problems/reverse-linked-list/' },
  'Palindrome Linked List': { lc: 'https://leetcode.com/problems/palindrome-linked-list/' },
  'Swap Nodes in Pairs': { lc: 'https://leetcode.com/problems/swap-nodes-in-pairs/' },
  'Odd Even Linked List (By Index)': { lc: 'https://leetcode.com/problems/odd-even-linked-list/' },
  'Reorder List': { lc: 'https://leetcode.com/problems/reorder-list/' },
  'Rotate List': { lc: 'https://leetcode.com/problems/rotate-list/' },
  'Add Two Numbers (Reverse Order)': { lc: 'https://leetcode.com/problems/add-two-numbers/' },
  'Add Two Numbers II (Forward Order)': { lc: 'https://leetcode.com/problems/add-two-numbers-ii/' },
  'Merge Two Sorted Lists': { lc: 'https://leetcode.com/problems/merge-two-sorted-lists/' },
  'Sort List (Merge Sort on LL)': { lc: 'https://leetcode.com/problems/sort-list/' },
  'Copy List with Random Pointer (Clone LL)': { lc: 'https://leetcode.com/problems/copy-list-with-random-pointer/' },
  'Flattening a Linked List': { gfg: 'https://practice.geeksforgeeks.org/problems/flattening-a-linked-list/1' },
  'Reverse Linked List in Groups of Size K': { lc: 'https://leetcode.com/problems/reverse-nodes-in-k-group/' },

  // ── STACKS ──
  'Implement Stack using Arrays': { gfg: 'https://practice.geeksforgeeks.org/problems/implement-stack-using-array/1' },
  'Implement Stack using Linked List': { gfg: 'https://practice.geeksforgeeks.org/problems/implement-stack-using-linked-list/1' },
  'Valid Parentheses': { lc: 'https://leetcode.com/problems/valid-parentheses/' },
  'Remove All Adjacent Duplicates In String': { lc: 'https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string/' },
  'Evaluate Reverse Polish Notation': { lc: 'https://leetcode.com/problems/evaluate-reverse-polish-notation/' },
  'Largest Rectangle in Histogram': { lc: 'https://leetcode.com/problems/largest-rectangle-in-histogram/' },
  'Min Stack (O(1) getMin)': { lc: 'https://leetcode.com/problems/min-stack/' },
  'Next Greater Element I': { lc: 'https://leetcode.com/problems/next-greater-element-i/' },
  'Next Greater Element II (Circular Array)': { lc: 'https://leetcode.com/problems/next-greater-element-ii/' },
  'Stock Span Problem': { gfg: 'https://practice.geeksforgeeks.org/problems/stock-span-problem-1587115621/1' },
  'Asteroid Collision': { lc: 'https://leetcode.com/problems/asteroid-collision/' },
  'Remove K Digits': { lc: 'https://leetcode.com/problems/remove-k-digits/' },
  'Maximal Rectangle (2D Grid)': { lc: 'https://leetcode.com/problems/maximal-rectangle/' },

  // ── QUEUES ──
  'Implement Queue using Arrays': { gfg: 'https://practice.geeksforgeeks.org/problems/implement-queue-using-array/1' },
  'Implement Queue using Stacks': { lc: 'https://leetcode.com/problems/implement-queue-using-stacks/' },
  'Implement Stack using Queues': { lc: 'https://leetcode.com/problems/implement-stack-using-queues/' },
  'Sliding Window Maximum': { lc: 'https://leetcode.com/problems/sliding-window-maximum/' },

  // ── BINARY TREES ──
  'Preorder Traversal (Recursive & Iterative)': { lc: 'https://leetcode.com/problems/binary-tree-preorder-traversal/' },
  'Inorder Traversal (Recursive & Iterative)': { lc: 'https://leetcode.com/problems/binary-tree-inorder-traversal/' },
  'Postorder Traversal (Recursive & Iterative)': { lc: 'https://leetcode.com/problems/binary-tree-postorder-traversal/' },
  'Binary Tree Level Order Traversal': { lc: 'https://leetcode.com/problems/binary-tree-level-order-traversal/' },
  'Binary Tree Zigzag Level Order Traversal': { lc: 'https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/' },
  'Maximum Depth of Binary Tree': { lc: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/' },
  'Same Tree': { lc: 'https://leetcode.com/problems/same-tree/' },
  'Invert Binary Tree': { lc: 'https://leetcode.com/problems/invert-binary-tree/' },
  'Symmetric Tree': { lc: 'https://leetcode.com/problems/symmetric-tree/' },
  'Diameter of Binary Tree': { lc: 'https://leetcode.com/problems/diameter-of-binary-tree/' },
  'Balanced Binary Tree': { lc: 'https://leetcode.com/problems/balanced-binary-tree/' },
  'Path Sum I': { lc: 'https://leetcode.com/problems/path-sum/' },
  'Path Sum II': { lc: 'https://leetcode.com/problems/path-sum-ii/' },
  'Lowest Common Ancestor of a Binary Tree': { lc: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/' },
  'Binary Tree Maximum Path Sum': { lc: 'https://leetcode.com/problems/binary-tree-maximum-path-sum/' },
  'Construct Binary Tree from Preorder and Inorder Traversal': { lc: 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/' },
  'Flatten Binary Tree to Linked List': { lc: 'https://leetcode.com/problems/flatten-binary-tree-to-linked-list/' },
  'Serialize and Deserialize Binary Tree': { lc: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/' },

  // ── BST ──
  'Search in a Binary Search Tree': { lc: 'https://leetcode.com/problems/search-in-a-binary-search-tree/' },
  'Insert into a Binary Search Tree': { lc: 'https://leetcode.com/problems/insert-into-a-binary-search-tree/' },
  'Validate Binary Search Tree': { lc: 'https://leetcode.com/problems/validate-binary-search-tree/' },
  'Kth Smallest Element in a BST': { lc: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/' },
  'Delete Node in a BST': { lc: 'https://leetcode.com/problems/delete-node-in-a-bst/' },
  'Lowest Common Ancestor of a Binary Search Tree': { lc: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/' },
  'Convert Sorted Array to Binary Search Tree': { lc: 'https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/' },
  'Balance a Binary Search Tree': { lc: 'https://leetcode.com/problems/balance-a-binary-search-tree/' },
  'Recover Binary Search Tree': { lc: 'https://leetcode.com/problems/recover-binary-search-tree/' },

  // ── TRIES ──
  'Implement Trie (Prefix Tree)': { lc: 'https://leetcode.com/problems/implement-trie-prefix-tree/' },
  'Design Add and Search Words Data Structure': { lc: 'https://leetcode.com/problems/design-add-and-search-words-data-structure/' },
  'Word Search II': { lc: 'https://leetcode.com/problems/word-search-ii/' },
  'Maximum XOR of Two Numbers in an Array': { lc: 'https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/' },

  // ── HASHMAPS ──
  'Contains Duplicate': { lc: 'https://leetcode.com/problems/contains-duplicate/' },
  'Valid Anagram (Hashmap Approach)': { lc: 'https://leetcode.com/problems/valid-anagram/' },
  'Unique Number of Occurrences': { lc: 'https://leetcode.com/problems/unique-number-of-occurrences/' },
  'Two Sum': { lc: 'https://leetcode.com/problems/two-sum/' },
  'Intersection of Two Arrays': { lc: 'https://leetcode.com/problems/intersection-of-two-arrays/' },
  'Group Anagrams': { lc: 'https://leetcode.com/problems/group-anagrams/' },
  'Longest Consecutive Sequence': { lc: 'https://leetcode.com/problems/longest-consecutive-sequence/' },
  'Subarray Sum Equals K': { lc: 'https://leetcode.com/problems/subarray-sum-equals-k/' },
  'Top K Frequent Elements': { lc: 'https://leetcode.com/problems/top-k-frequent-elements/' },
  'LRU Cache (Least Recently Used)': { lc: 'https://leetcode.com/problems/lru-cache/' },
  'LFU Cache (Least Frequently Used)': { lc: 'https://leetcode.com/problems/lfu-cache/' },

  // ── HEAPS ──
  'Kth Largest Element in an Array': { lc: 'https://leetcode.com/problems/kth-largest-element-in-an-array/' },
  'K Closest Points to Origin': { lc: 'https://leetcode.com/problems/k-closest-points-to-origin/' },
  'Top K Frequent Elements (Heap Approach)': { lc: 'https://leetcode.com/problems/top-k-frequent-elements/' },
  'Merge K Sorted Lists': { lc: 'https://leetcode.com/problems/merge-k-sorted-lists/' },
  'Kth Smallest Element in a Sorted Matrix': { lc: 'https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/' },
  'Task Scheduler': { lc: 'https://leetcode.com/problems/task-scheduler/' },
  'Reorganize String': { lc: 'https://leetcode.com/problems/reorganize-string/' },
  'Find Median from Data Stream': { lc: 'https://leetcode.com/problems/find-median-from-data-stream/' },

  // ── PREFIX SUM ──
  'Running Sum of 1D Array': { lc: 'https://leetcode.com/problems/running-sum-of-1d-array/' },
  'Find the Highest Altitude': { lc: 'https://leetcode.com/problems/find-the-highest-altitude/' },
  'Find Pivot Index': { lc: 'https://leetcode.com/problems/find-pivot-index/' },
  'Range Sum Query - Immutable': { lc: 'https://leetcode.com/problems/range-sum-query-immutable/' },
  'Product of Array Except Self': { lc: 'https://leetcode.com/problems/product-of-array-except-self/' },
  'Trapping Rain Water (Prefix Max / Min)': { lc: 'https://leetcode.com/problems/trapping-rain-water/' },

  // ── TWO POINTERS ──
  'Move Zeroes (Two Pointer Intuition)': { lc: 'https://leetcode.com/problems/move-zeroes/' },
  'Valid Palindrome (Two Pointers)': { lc: 'https://leetcode.com/problems/valid-palindrome/' },
  'Two Sum II - Input Array Is Sorted': { lc: 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/' },
  'Sort Colors (Dutch National Flag)': { lc: 'https://leetcode.com/problems/sort-colors/' },
  'Container With Most Water': { lc: 'https://leetcode.com/problems/container-with-most-water/' },
  '3Sum': { lc: 'https://leetcode.com/problems/3sum/' },
  'Minimum Size Subarray Sum': { lc: 'https://leetcode.com/problems/minimum-size-subarray-sum/' },
  'Longest Substring Without Repeating Characters': { lc: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/' },
  'Longest Repeating Character Replacement': { lc: 'https://leetcode.com/problems/longest-repeating-character-replacement/' },
  'Find All Anagrams in a String': { lc: 'https://leetcode.com/problems/find-all-anagrams-in-a-string/' },
  'Minimum Window Substring': { lc: 'https://leetcode.com/problems/minimum-window-substring/' },

  // ── GREEDY ──
  'Assign Cookies': { lc: 'https://leetcode.com/problems/assign-cookies/' },
  'Lemonade Change': { lc: 'https://leetcode.com/problems/lemonade-change/' },
  'Jump Game': { lc: 'https://leetcode.com/problems/jump-game/' },
  'Jump Game II': { lc: 'https://leetcode.com/problems/jump-game-ii/' },
  'Gas Station': { lc: 'https://leetcode.com/problems/gas-station/' },
  'Candy': { lc: 'https://leetcode.com/problems/candy/' },
  'Non-overlapping Intervals': { lc: 'https://leetcode.com/problems/non-overlapping-intervals/' },
  'Minimum Number of Arrows to Burst Balloons': { lc: 'https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/' },
  'Course Schedule III': { lc: 'https://leetcode.com/problems/course-schedule-iii/' },

  // ── GRAPHS ──
  'Number of Islands': { lc: 'https://leetcode.com/problems/number-of-islands/' },
  'Number of Provinces': { lc: 'https://leetcode.com/problems/number-of-provinces/' },
  'Clone Graph': { lc: 'https://leetcode.com/problems/clone-graph/' },
  'Is Graph Bipartite?': { lc: 'https://leetcode.com/problems/is-graph-bipartite/' },
  'Flood Fill': { lc: 'https://leetcode.com/problems/flood-fill/' },
  'Max Area of Island': { lc: 'https://leetcode.com/problems/max-area-of-island/' },
  'Rotting Oranges': { lc: 'https://leetcode.com/problems/rotting-oranges/' },
  'Course Schedule': { lc: 'https://leetcode.com/problems/course-schedule/' },
  'Course Schedule II': { lc: 'https://leetcode.com/problems/course-schedule-ii/' },
  "Dijkstra's Algorithm": { gfg: 'https://practice.geeksforgeeks.org/problems/implementing-dijkstra-set-1-adjacency-matrix/1' },
  'Network Delay Time': { lc: 'https://leetcode.com/problems/network-delay-time/' },
  'Cheapest Flights Within K Stops': { lc: 'https://leetcode.com/problems/cheapest-flights-within-k-stops/' },
  'Accounts Merge': { lc: 'https://leetcode.com/problems/accounts-merge/' },
  'Redundant Connection': { lc: 'https://leetcode.com/problems/redundant-connection/' },
  'Word Ladder': { lc: 'https://leetcode.com/problems/word-ladder/' },
  'Word Ladder II': { lc: 'https://leetcode.com/problems/word-ladder-ii/' },

  // ── BACKTRACKING ──
  'Subsets / Power Set': { lc: 'https://leetcode.com/problems/subsets/' },
  'Subsets II (With Duplicates)': { lc: 'https://leetcode.com/problems/subsets-ii/' },
  'Combination Sum I': { lc: 'https://leetcode.com/problems/combination-sum/' },
  'Combination Sum II': { lc: 'https://leetcode.com/problems/combination-sum-ii/' },
  'Combination Sum III': { lc: 'https://leetcode.com/problems/combination-sum-iii/' },
  'Letter Combinations of a Phone Number': { lc: 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/' },
  'Generate Parentheses': { lc: 'https://leetcode.com/problems/generate-parentheses/' },
  'Palindrome Partitioning': { lc: 'https://leetcode.com/problems/palindrome-partitioning/' },
  'Word Search': { lc: 'https://leetcode.com/problems/word-search/' },
  'N-Queens': { lc: 'https://leetcode.com/problems/n-queens/' },
  'N-Queens II': { lc: 'https://leetcode.com/problems/n-queens-ii/' },
  'Sudoku Solver': { lc: 'https://leetcode.com/problems/sudoku-solver/' },

  // ── DYNAMIC PROGRAMMING ──
  'Climbing Stairs': { lc: 'https://leetcode.com/problems/climbing-stairs/' },
  'Min Cost Climbing Stairs': { lc: 'https://leetcode.com/problems/min-cost-climbing-stairs/' },
  'House Robber': { lc: 'https://leetcode.com/problems/house-robber/' },
  'House Robber II': { lc: 'https://leetcode.com/problems/house-robber-ii/' },
  'Decode Ways': { lc: 'https://leetcode.com/problems/decode-ways/' },
  'Unique Paths': { lc: 'https://leetcode.com/problems/unique-paths/' },
  'Unique Paths II': { lc: 'https://leetcode.com/problems/unique-paths-ii/' },
  'Minimum Path Sum': { lc: 'https://leetcode.com/problems/minimum-path-sum/' },
  'Triangle': { lc: 'https://leetcode.com/problems/triangle/' },
  'Partition Equal Subset Sum': { lc: 'https://leetcode.com/problems/partition-equal-subset-sum/' },
  '0/1 Knapsack Problem': { gfg: 'https://practice.geeksforgeeks.org/problems/0-1-knapsack-problem0945/1' },
  'Coin Change': { lc: 'https://leetcode.com/problems/coin-change/' },
  'Coin Change II': { lc: 'https://leetcode.com/problems/coin-change-ii/' },
  'Perfect Squares': { lc: 'https://leetcode.com/problems/perfect-squares/' },
  'Longest Common Subsequence': { lc: 'https://leetcode.com/problems/longest-common-subsequence/' },
  'Edit Distance': { lc: 'https://leetcode.com/problems/edit-distance/' },
  'Longest Palindromic Subsequence': { lc: 'https://leetcode.com/problems/longest-palindromic-subsequence/' },
  'Distinct Subsequences': { lc: 'https://leetcode.com/problems/distinct-subsequences/' },
  'Wildcard Matching': { lc: 'https://leetcode.com/problems/wildcard-matching/' },
  'Regular Expression Matching': { lc: 'https://leetcode.com/problems/regular-expression-matching/' },
  'Best Time to Buy and Sell Stock II': { lc: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/' },
  'Best Time to Buy and Sell Stock III': { lc: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/' },
  'Best Time to Buy and Sell Stock IV': { lc: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/' },
  'Longest Increasing Subsequence': { lc: 'https://leetcode.com/problems/longest-increasing-subsequence/' },
  'Russian Doll Envelopes': { lc: 'https://leetcode.com/problems/russian-doll-envelopes/' },
  'Matrix Chain Multiplication': { gfg: 'https://practice.geeksforgeeks.org/problems/matrix-chain-multiplication0303/1' },
  'Burst Balloons': { lc: 'https://leetcode.com/problems/burst-balloons/' },
  'Palindrome Partitioning II': { lc: 'https://leetcode.com/problems/palindrome-partitioning-ii/' },
}
